### ISSUE TITLE
Crash when Export

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#107]
On Latest HEAD 93a75dd
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/fontView.py", line 852, in export
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/__init__.py", line 88, in compile
    partsCompiler.compile()
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/makeotfParts.py", line 95, in compile
    self.setupFile_outlineSource(self.paths["outlineSource"])
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/makeotfParts.py", line 110, in setupFile_outlineSource
    c.compile()
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/outlineOTF.py", line 75, in compile
    self.setupTable_OS2()
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/outlineOTF.py", line 382, in setupTable_OS2
    os2.achVendID = str(getAttrWithFallback(font.info, "openTypeOS2VendorID").decode("ascii", "ignore"))
AttributeError: 'str' object has no attribute 'decode'
Abort trap: 6
```

**Comment by adrientetar** [comment]
Fixed thanks

**Comment by adrientetar** [comment]
I just pushed another fix that should be enough to get it to work.

**Comment by pathumego** [comment]
@adrientetar Im getting different errors and not sure if its something wrong with the file.

This is with a UFO file exported from FF.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/fontView.py", line 852, in export
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/__init__.py", line 88, in compile
    partsCompiler.compile()
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/makeotfParts.py", line 95, in compile
    self.setupFile_outlineSource(self.paths["outlineSource"])
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/makeotfParts.py", line 110, in setupFile_outlineSource
    c.compile()
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/outlineOTF.py", line 75, in compile
    self.setupTable_OS2()
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/outlineOTF.py", line 384, in setupTable_OS2
    os2.sxHeight = _roundInt(getAttrWithFallback(font.info, "xHeight"))
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/fontInfoData.py", line 408, in getAttrWithFallback
    value = staticFallbackData[attr]
KeyError: 'xHeight'
Abort trap: 6

```

This is when I try to just draw a single glyph and try to export.

```
Pathums-MacBook-Pro:trufont Pathum$ python3 -m defconQt ;
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/fontView.py", line 852, in export
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/__init__.py", line 88, in compile
    partsCompiler.compile()
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/makeotfParts.py", line 96, in compile
    self.setupFile_menuName(self.paths["menuName"])
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/makeotfParts.py", line 136, in setupFile_menuName
    encodedFamilyName = winStr(familyName)
  File "/usr/local/lib/python3.5/site-packages/ufo2fdk/featureTableWriter.py", line 95, in winStr
    return "".join([winCharEncode(c) for c in text])
TypeError: 'NoneType' object is not iterable
Abort trap: 6
```

**Comment by adrientetar** [comment]
Currently the font file needs at least a family name and style name to proceed.

**Comment by adrientetar** [comment]
The other crash is there's no fallback for OS/2 xHeight but the code asks for one.

**Comment by pathumego** [comment]
@adrientetar Cool thanks!

**Comment by adrientetar** [comment]
There is now an error message if minimal attributes are absent.

**Comment by pathumego** [comment]
👍
