### ISSUE TITLE
Startup Crash on current master

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#112]
It seems that **glyph = self.newGlyph(name)** is returning **None** for some reason:

```bash
felipe@guarana:~/devel/github_felipesanches/trufont/Lib$ git reset --hard 
HEAD is now at b39327b Merge pull request #111 from trufont/patch-14
felipe@guarana:~/devel/github_felipesanches/trufont/Lib$ git fetch upstream master
From https://github.com/trufont/trufont
 * branch            master     -> FETCH_HEAD
felipe@guarana:~/devel/github_felipesanches/trufont/Lib$ git rebase upstream/master 
Current branch master is up to date.
felipe@guarana:~/devel/github_felipesanches/trufont/Lib$ python3 -m defconQt 
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/felipe/devel/github_felipesanches/trufont/Lib/defconQt/__main__.py", line 29, in <module>
    main()
  File "/home/felipe/devel/github_felipesanches/trufont/Lib/defconQt/__main__.py", line 24, in main
    window = MainWindow(font)
  File "/home/felipe/devel/github_felipesanches/trufont/Lib/defconQt/fontView.py", line 640, in __init__
    self.newFile(True)
  File "/home/felipe/devel/github_felipesanches/trufont/Lib/defconQt/fontView.py", line 759, in newFile
    font.newStandardGlyph(name, asTemplate=True)
  File "/home/felipe/devel/github_felipesanches/trufont/Lib/defconQt/objects/defcon.py", line 23, in newStandardGlyph
    glyph.width = width
AttributeError: 'NoneType' object has no attribute 'width'
felipe@guarana:~/devel/github_felipesanches/trufont/Lib$
```

**Comment by adrientetar** [comment]
Update defcon.

**Comment by felipesanches** [comment]
thanks.

**Comment by felipesanches** [comment]
I do have the current python3-ufo3 branch from your adrientetar/defcon repository installed and I still have this crash. Which branch of defcon should we be using as a reference for development?

**Comment by adrientetar** [comment]
Always trufont packages, not my private forks.

**Comment by felipesanches** [comment]
oh, I see. It makes sense, indeed.
