### ISSUE TITLE
Use GlyphOrderAndAliasDB or .enc files to deal with glyph sets

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#122]
It is not clear how how the glyph sets work.

- [ ] If I need to add new glyphs with both a name and unicode point (Sinhala glyph unicode block with names) how do I do that? Right now I will have to add the unicode codepoints in `Settings>Glyph Sets` and manually rename glyphs after adding them with `Font>Add Glyphs` I think it would be much easier and make sense to use GlyphOrderAndAliasDB files for this.

- [ ] And if we can keep these as separate files in a `preferences` or some other folder, it will be easier.

**Comment by adrientetar** [comment]
9b2bc47a73a1e453aed95df907b1b120bd32b7b4

**Comment by pathumego** [comment]
@adrientetar How dose this work? Should it be in a txt file? or GOADB format? I gave in a pat and when I try to relaunch Trufont I get this

```
Pathums-MacBook-Pro:Lib Pathum$ python3 -m defconQt
warning: syntax error in glyphlist: %s
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/__main__.py", line 35, in <module>
    main()
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/__main__.py", line 29, in main
    app.GL2UV = glyphList.parseGlyphList(glyphListPath)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/util/glyphList.py", line 16, in parseGlyphList
    glyphName = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by adrientetar** [comment]
It should be e.g. `A;0041`, one per line.

**Comment by pathumego** [comment]
@adrientetar Thanks!! I ahve some suggestions to make it more user friendly. But I think it all that should go with #24 :)

**Comment by adrientetar** [comment]
Cool, thanks for bringing this to my attention.
