### ISSUE TITLE
AttributeError when running `trufont` from console without passing a .ufo filename

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#126]
Running from the current HEAD, if I execute `trufont` from the Terminal without also passing in a UFO path name, I get this error:
 
```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/trufont/bin/trufont", line 9, in <module>
    load_entry_point('defconQt==0.2.0', 'gui_scripts', 'trufont')()
  File "/Users/cosimolupo/Documents/Github/trufont/Lib/defconQt/__main__.py", line 30, in main
    window = MainWindow(font)
  File "/Users/cosimolupo/Documents/Github/trufont/Lib/defconQt/fontView.py", line 641, in __init__
    self.newFile(True)
  File "/Users/cosimolupo/Documents/Github/trufont/Lib/defconQt/fontView.py", line 760, in newFile
    font.newStandardGlyph(name, asTemplate=True)
  File "/Users/cosimolupo/Documents/Github/trufont/Lib/defconQt/objects/defcon.py", line 24, in newStandardGlyph
    glyph.width = width
AttributeError: 'NoneType' object has no attribute 'width'
```

**Comment by adrientetar** [comment]
Yeah, you need to update defcon for this to work.

**Comment by anthrotype** [comment]
Yeah, sorry :)

**Comment by adrientetar** [comment]
np!
