### ISSUE TITLE
Crash when using Knife

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#127]
On HEAD
```
Pathums-MacBook-Pro:Lib Pathum$ python3 -m defconQt
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1646, in mouseReleaseEvent
    self.knifeMouseRelease(event)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1836, in knifeMouseRelease
    for loc, ts in reversed(list(self._cachedIntersections.items())):
AttributeError: 'NoneType' object has no attribute 'items'
Abort trap: 6
```

**Comment by adrientetar** [comment]
e76c9c366ac30d6fb5941531810dcbe12bbeed96
