### ISSUE TITLE
CRASH Knife tool on Single segment path

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#130]
When Knife tool is used on a single segment path, it crashes

```
Pathums-MacBook-Pro:Lib Pathum$ python3 -m defconQt
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1646, in mouseReleaseEvent
    self.knifeMouseRelease(event)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1841, in knifeMouseRelease
    contour.splitAndInsertPointAtSegmentAndT(index, t / prev)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/contour.py", line 527, in splitAndInsertPointAtSegmentAndT
    self._splitAndInsertAtSegmentAndT(segmentIndex, t, True)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/contour.py", line 552, in _splitAndInsertAtSegmentAndT
    raise NotImplementedError("unknown segment type: %s" % segmentType)
NotImplementedError: unknown segment type: move
Abort trap: 6
```

**Comment by adrientetar** [comment]
3a5d1a3bba81cd5c1b751f435f1d034c6582bb91
