### ISSUE TITLE
Build from source error

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#158]
I got this,
```
Pathums-MacBook-Pro:trufont Pathum$ sudo pip install -r requirements.txt
The directory '/Users/Pathum/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Pathum/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting booleanOperations from git+https://github.com/typemytype/booleanOperations.git#egg=booleanOperations (from -r requirements.txt (line 1))
  Cloning https://github.com/typemytype/booleanOperations.git to /private/tmp/pip-build-_V3zR9/booleanOperations
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-_V3zR9/booleanOperations/setup.py", line 11, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-_V3zR9/booleanOperations
```

And `sudo -H` got this
```
Pathums-MacBook-Pro:trufont Pathum$ sudo -H pip install -r requirements.txt
Collecting booleanOperations from git+https://github.com/typemytype/booleanOperations.git#egg=booleanOperations (from -r requirements.txt (line 1))
  Cloning https://github.com/typemytype/booleanOperations.git to /private/tmp/pip-build-uZeywy/booleanOperations
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-uZeywy/booleanOperations/setup.py", line 11, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-uZeywy/booleanOperations
Pathums-MacBook-Pro:trufont Pathum$ 
```

**Comment by adrientetar** [comment]
Install cython.

**Comment by pathumego** [comment]
should cython be listed as a dependency?

**Comment by adrientetar** [comment]
Yes.

**Comment by pathumego** [comment]
@adrientetar Get this when I try to run..
```
Pathums-MacBook-Pro:trufont Pathum$ python3 -m defconQt;
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/__main__.py", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/representationFactories/__init__.py", line 4, in <module>
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/representationFactories/glyphViewFactory.py", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/objects/defcon.py", line 1, in <module>
ImportError: No module named 'booleanOperations'
```

**Comment by adrientetar** [comment]
Install booleanOperations.

**Comment by pathumego** [comment]
Ok i did that, 

Now I get this
```
Pathums-MacBook-Pro:trufont Pathum$ python3 -m defconQt 
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/__main__.py", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/representationFactories/__init__.py", line 4, in <module>
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/representationFactories/glyphViewFactory.py", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/objects/defcon.py", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/booleanOperations/__init__.py", line 1, in <module>
    from booleanOperationManager import BooleanOperationManager
ImportError: No module named 'booleanOperationManager'
```

**Comment by adrientetar** [comment]
Have you downloaded the latest version from https://github.com/typemytype/booleanOperations.git ?

This looks like an old version.

**Comment by anthrotype** [comment]
yes, he's using an older version. that line was changed with commit https://github.com/typemytype/booleanOperations/commit/5126974d7c721af8a086326137018ffe19a5abda

**Comment by adrientetar** [comment]
Not a fan of relative imports btw.

**Comment by anthrotype** [comment]
yeah, they have advantages as well as disadvantages

Anyway, that's not why the `pip install -r requirements.txt` was failing above.

I just made some change to simplify the setup process of booleanOperations. This should fix the error about Cython not being installed: https://github.com/typemytype/booleanOperations/pull/15

The problem with pip is that in the `requirements.txt`, we use `git+https://...` kinds of pip requirements. Now, if the `sudo pip install -r requirements.txt` is run more than once, the second time pip will tell you the requirements are already satisfied, even though they might have changed upstream.
That is because we are telling it to install the package named "x" to site-packages but we are not also specifying a version number which can be used to compare against the installed package.

The solution is either doing `sudo pip install --upgrade -r requirements.txt`, or change all the requirements which are cloned from a git repo this way: `-e git+htts://...` so that they will be installed in editable (or develop) mode. In the latter case, when the pip install command is run again, the local repository synchronises with the upstream repo and the .egg_link will still work.

**Comment by adrientetar** [comment]
Editable mode sounds good. Do you want to submit a PR for it?
