### ISSUE TITLE
Crash while drawing on a glyph with componants

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#163]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/glyphView.py", line 934, in mouseMoveEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/glyphView.py", line 922, in _redirectEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/tools/penTool.py", line 111, in mouseMoveEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/tools/baseTool.py", line 44, in magnetPos
AttributeError: 'TComponent' object has no attribute 'x'
Abort trap: 6
```

**Comment by adrientetar** [comment]
I can't reproduce this, can you explain how to do it?

**Comment by pathumego** [comment]
@adrientetar Im having the problem with this file https://drive.google.com/open?id=0B-5mpXa8HrFVeVF5bmpCRHhjU2s

When I open this UFO and try to draw on any glyph with componants above crash happens. On Mac with

**Comment by adrientetar** [comment]
Thanks for the repro.

53605867bcc54488d118b5162e4e14f977ec434f
