### ISSUE TITLE
Crash while opening a ufo

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#177]
This happend while opening a ufo with only one A glyph which the widht is around 8000.

```
Pathums-MacBook-Pro:~ Pathum$ /Users/Pathum/src/github.com/trufont/trufont.command ; exit;
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/fontView.py", line 867, in openFile
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/fontView.py", line 717, in __init__
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/fontView.py", line 1106, in _set_font
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/fontView.py", line 1116, in _set_sortDescriptor
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/fontView.py", line 1209, in updateGlyphsFromFont
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/font.py", line 218, in __getitem__
    return self._glyphSet[name]
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/layer.py", line 250, in __getitem__
    self.loadGlyph(name)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/layer.py", line 173, in loadGlyph
    self._glyphSet.readGlyph(glyphName=name, glyphObject=glyph, pointPen=pointPen)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/robofab/Lib/ufoLib/glifLib.py", line 316, in readGlyph
    _readGlyphFromTree(tree, glyphObject, pointPen, formatVersions=formatVersions)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/robofab/Lib/ufoLib/glifLib.py", line 856, in _readGlyphFromTree
    _readGlyphFromTreeFormat1(tree=tree, glyphObject=glyphObject, pointPen=pointPen)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/robofab/Lib/ufoLib/glifLib.py", line 877, in _readGlyphFromTreeFormat1
    buildOutlineFormat1(glyphObject, pointPen, children)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/robofab/Lib/ufoLib/glifLib.py", line 1064, in buildOutlineFormat1
    _buildOutlineContourFormat1(pen, (attrs, children))
  File "/Users/Pathum/src/github.com/trufont/trufont/src/robofab/Lib/ufoLib/glifLib.py", line 1095, in _buildOutlineContourFormat1
    children = _validateAndMassagePointStructures(children, pointAttributesFormat1, openContourOffCurveLeniency=True)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/robofab/Lib/ufoLib/glifLib.py", line 1305, in _validateAndMassagePointStructures
    raise GlifLibError("line can not have an offcurve.")
ufoLib.glifLib.GlifLibError: line can not have an offcurve.
/Users/Pathum/src/github.com/trufont/trufont.command: line 1: 16833 Abort trap: 6           python3 -m defconQt
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by adrientetar** [comment]
This crash is the same as #155, there's an invalid line segment in A.glif. In #155 it was a path originally made under illustrator and copied into glyphsapp then exported to ufo that gave an invalid segment like this. @schriftgestalt is looking into it.

What should be changed in TruFont is displaying an error message for it but that's about it.

**Comment by adrientetar** [comment]
You can fix that in a text editor, btw.

**Comment by adrientetar** [comment]
93df2648a9b8369931c28b4ba484c3a095d26a1e should display an error message when an invalid font is opened.

**Comment by pathumego** [comment]
@adrientetar Thanks!
