### ISSUE TITLE
ImportError: cannot import name 'PointToSegmentPen'

### ISSUE THREAD

**Issue by madig** [trufont/trufont#179]
Trying master, can't open UFOs, aborts with above error. Did a `pip3 install --upgrade --user -r requirements.txt` before.

**Comment by adrientetar** [comment]
Can you post the full traceback?

**Comment by madig** [comment]
```
Traceback (most recent call last):
  File "/home/nikolaus/Entwicklung/trufont/Lib/defconQt/glyphCollectionView.py", line 585, in paintEvent
    outline = glyph.getRepresentation("defconQt.QPainterPath")
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/home/nikolaus/Entwicklung/trufont/Lib/defconQt/representationFactories/qPainterPathFactory.py", line 7, in QPainterPathFactory
    glyph.draw(pen)
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/glyph.py", line 367, in draw
    from ufoLib.pointPen import PointToSegmentPen
ImportError: cannot import name 'PointToSegmentPen'
Traceback (most recent call last):
  File "/home/nikolaus/Entwicklung/trufont/Lib/defconQt/glyphCollectionView.py", line 585, in paintEvent
    outline = glyph.getRepresentation("defconQt.QPainterPath")
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/home/nikolaus/Entwicklung/trufont/Lib/defconQt/representationFactories/qPainterPathFactory.py", line 7, in QPainterPathFactory
    glyph.draw(pen)
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/glyph.py", line 367, in draw
    from ufoLib.pointPen import PointToSegmentPen
ImportError: cannot import name 'PointToSegmentPen'
```

**Comment by adrientetar** [comment]
Are you sure that you have the latest ufoLib from https://github.com/unified-font-object/ufoLib.git installed?

**Comment by madig** [comment]
```
$ pip3 install --upgrade --user -r requirements.txt
Requirement already up-to-date: setuptools>=18.0 in /home/nikolaus/.local/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Obtaining booleanOperations from git+https://github.com/typemytype/booleanOperations.git#egg=booleanOperations (from -r requirements.txt (line 2))
  Updating ./src/booleanoperations clone
Obtaining fonttools from git+https://github.com/behdad/fonttools.git#egg=fonttools (from -r requirements.txt (line 3))
  Updating ./src/fonttools clone
Obtaining ufoLib from git+https://github.com/unified-font-object/ufoLib.git#egg=ufoLib (from -r requirements.txt (line 4))
  Updating ./src/ufolib clone
Obtaining defcon from git+https://github.com/trufont/defcon.git@python3-ufo3#egg=defcon (from -r requirements.txt (line 5))
  Updating ./src/defcon clone (to python3-ufo3)
Obtaining ufo2fdk from git+https://github.com/trufont/ufo2fdk.git@python3-ufo3#egg=ufo2fdk (from -r requirements.txt (line 6))
  Updating ./src/ufo2fdk clone (to python3-ufo3)
Installing collected packages: booleanOperations, fonttools, ufoLib, defcon, ufo2fdk
  Running setup.py develop for booleanOperations
  Running setup.py develop for fonttools
  Running setup.py develop for ufoLib
  Running setup.py develop for defcon
  Running setup.py develop for ufo2fdk
Successfully installed booleanOperations-0.2 defcon-0.1 fonttools-3.0 ufo2fdk-0.1 ufoLib-1.2
```

Should be installed...

**Comment by adrientetar** [comment]
Can you try to install ufoLib manually with `python setup.py install`? 
On my machine `from ufoLib.pointPen import PointToSegmentPen` works&hellip;

**Comment by madig** [comment]
Installed using `sudo python3 setup.py install`, doesn't work :(

**Comment by adrientetar** [comment]
I don't really know what this is... can you maybe look at the place where packages are installed on your system and verify that ufoLib has PointToSegmentPen in pointPen.py

**Comment by madig** [comment]
I think I found something:
```
~/.local/lib/python3.4/site-packages/ufoLib/glifLib.py
79:		from robofab.pens.adapterPens import PointToSegmentPen
80:		pointPen = PointToSegmentPen(pen)
```
;)

**Comment by madig** [comment]
Okay, I deleted all my local user packages and did a fresh install of the requirements. It works now. Sorry for wasting your time.

**Comment by adrientetar** [comment]
Cool, yea ufoLib switched from robofab repo to its own so there must have been a caching problem of some sort.
