### ISSUE TITLE
missing robofab dependency (still required by defcon) cause tests to fail

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#189]
robofab was recently removed from trufont's `requirements.txt`. However, it is still being imported by defcon (python3-ufo3):

https://github.com/trufont/defcon/blob/python3-ufo3/Lib/defcon/pens/decomposeComponentPointPen.py#L2

Here's what I get when I do `python setup.py test` after I `pip install -r requirements.txt` (without robofab) in a fresh virtual enviroment:

```
ERROR: fontInfo_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: fontInfo_test
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/cosimolupo/Documents/Github/trufont/tests/defconQt/fontInfo_test.py", line 6, in <module>
    from defconQt.fontView import Application, MainWindow
  File "/Users/cosimolupo/Documents/Github/trufont/Lib/defconQt/fontView.py", line 5, in <module>
    from defconQt.glyphView import MainGlyphWindow
  File "/Users/cosimolupo/Documents/Github/trufont/Lib/defconQt/glyphView.py", line 2, in <module>
    from defconQt.objects.defcon import TGlyph
  File "/Users/cosimolupo/Documents/Github/trufont/Lib/defconQt/objects/defcon.py", line 1, in <module>
    from booleanOperations.booleanGlyph import BooleanGlyph
  File "/usr/local/var/pyenv/versions/trufont/src/booleanoperations/Lib/booleanOperations/booleanGlyph.py", line 5, in <module>
    from robofab.pens.pointPen import AbstractPointPen
ImportError: No module named 'robofab.pens'
```

I suspect that this is the reason why the Travis build is also failing. The unittest module cannot load the tests from the `fontInfo_test` module because of the ImportError exception (though Travis somehow isn't showing the full traceback).

cc @adrientetar https://github.com/trufont/trufont/commit/9e47ff1ac67106321b48d1dbdbfe7584546f888c#commitcomment-15303128

**Comment by adrientetar** [comment]
Thanks for the thorough analysis! I purged robofab from my machine and indeed I found quite some blockers.

I changed calls to robofab in booleanOperations fork to use ufoLib instead, do you think that this is upstreamable? 
We can use try/except if upstream is not ready to switch to ufoLib just yet.

**Comment by anthrotype** [comment]
cool! I'm sure Frederik will be happy if you submit a PR.
