### ISSUE TITLE
Crash when deleting a point

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#196]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/glyphView.py", line 952, in keyPressEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/glyphView.py", line 949, in _redirectEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/tools/selectionTool.py", line 135, in keyPressEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/util/uiMethods.py", line 98, in removeUISelection
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/contour.py", line 340, in removeSegment
    nextSegment = segments[nextIndex]
IndexError: list index out of range
Abort trap: 6
```

**Comment by pathumego** [comment]
Deleting off curve point on a end point of an open contour:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/glyphView.py", line 967, in keyPressEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/glyphView.py", line 964, in _redirectEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/tools/selectionTool.py", line 135, in keyPressEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/util/uiMethods.py", line 98, in removeUISelection
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/contour.py", line 340, in removeSegment
    nextSegment = segments[nextIndex]
IndexError: list index out of range
```

**Comment by adrientetar** [comment]
Is this fixed with current trufont and defcon?

**Comment by pathumego** [comment]
Yep Thanks!
