### ISSUE TITLE
Can not export a font with simple shape

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#209]
<img width="456" alt="screen shot 2016-01-24 at 12 17 01 am" src="https://cloud.githubusercontent.com/assets/6846609/12533688/35256f20-c230-11e5-91d0-8e3858d44586.png">
<img width="532" alt="screen shot 2016-01-24 at 12 16 19 am" src="https://cloud.githubusercontent.com/assets/6846609/12533689/3530a20a-c230-11e5-8734-9f3081bb0c2e.png">

**Comment by adrientetar** [comment]
Yes ufo2ft is currently broken.

**Comment by anthrotype** [comment]
full traceback?

**Comment by adrientetar** [comment]
Btw, as of da13f19834f24625a1bca9e9a75896e1698fb165 you can now access full traceback from the error window.

**Comment by pathumego** [comment]
@anthrotype 
```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/fontView.py", line 946, in exportFile
    otf = self.font.getRepresentation("defconQt.TTFont")
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/representationFactories/openTypeFactory.py", line 5, in TTFontFactory
    otf = compileOTF(font)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/__init__.py", line 29, in compileOTF
    featureCompilerClass, kernWriter, markWriter)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/__init__.py", line 14, in _compile
    outline = outlineCompiler.compile()
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/outlineOTF.py", line 66, in compile
    self.setupTable_name()
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/outlineOTF.py", line 242, in setupTable_name
    familyName = getAttrWithFallback(font.info, "styleMapFamilyName")
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/fontInfoData.py", line 411, in getAttrWithFallback
    value = specialFallbacks[attr](info)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/fontInfoData.py", line 43, in styleMapFamilyNameFallback
    return (familyName + " " + styleName).strip()
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Comment by anthrotype** [comment]
it means that your UFO does not have a "familyName" (nor an "openTypeNamePreferredFamilyName", which would fall back to the latter), so it fails to concatenate a `None` with a `str`.

Set the "familyName" or maybe file an issue at the upstream repo?

**Comment by anthrotype** [comment]
the first error message in the picture was different though. Do you have a traceback for that one as well?

**Comment by pathumego** [comment]
Yep managed to reproduce it. This is with some names in font info

```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/fontView.py", line 946, in exportFile
    otf = self.font.getRepresentation("defconQt.TTFont")
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/representationFactories/openTypeFactory.py", line 5, in TTFontFactory
    otf = compileOTF(font)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/__init__.py", line 29, in compileOTF
    featureCompilerClass, kernWriter, markWriter)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/__init__.py", line 18, in _compile
    featureCompiler.compile()
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/makeotfParts.py", line 26, in compile
    self.setupFile_features()
  File "/Users/Pathum/src/github.com/trufont/trufont/src/ufo2ft/Lib/ufo2ft/makeotfParts.py", line 58, in setupFile_features
    if self.overwriteFeatures or not kernRE.search(existing):
TypeError: expected string or bytes-like object

```

**Comment by anthrotype** [comment]
That is probably because the variable `existing = self.font.features.text` returns None (i.e. the defcon Font has no features), and `kernRE.search(existing)` is expecting str or bytes.

https://github.com/jamesgk/ufo2ft/blob/master/Lib/ufo2ft/makeotfParts.py#L54

another issue to report upstream. Mind doing that?

**Comment by pathumego** [comment]
@anthrotype Not a prob. So both should be reported in https://github.com/jamesgk/ufo2ft? This traceback is sufficent?

**Comment by anthrotype** [comment]
yeah. maybe point to this issue as well. Thanks

**Comment by adrientetar** [comment]
google18n/ufo2ft#17 should fix this.
