### ISSUE TITLE
Crash/can't save if "loose offcurve point", can't continue open contour

### ISSUE THREAD

**Issue by madig** [trufont/trufont#214]
1. Pen a corner point followed by a smooth point
2. Try to save
3. Deselect points and select last point again, try to continue/close contour

Sometimes crashes, sometimes:
```
Traceback (most recent call last):
  File "/home/nikolaus/.local/lib/python3.4/site-packages/defconQt-0.3.0-py3.4.egg/defconQt/fontView.py", line 901, in saveFile
  File "/home/nikolaus/.local/lib/python3.4/site-packages/defconQt-0.3.0-py3.4.egg/defconQt/objects/defcon.py", line 41, in save
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/font.py", line 742, in save
    self.layers.save(writer, saveAs=saveAs, progressBar=progressBar)
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/layerSet.py", line 317, in save
    layer.save(glyphSet, saveAs=saveAs, progressBar=progressBar)
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/layer.py", line 608, in save
    self.saveGlyph(glyph, glyphSet, saveAs=saveAs)
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/layer.py", line 624, in saveGlyph
    glyphSet.writeGlyph(glyph.name, glyph, glyph.drawPoints)
  File "/home/nikolaus/Entwicklung/trufont/src/ufolib/Lib/ufoLib/glifLib.py", line 353, in writeGlyph
    data = writeGlyphToString(glyphName, glyphObject, drawPointsFunc, formatVersion=formatVersion)
  File "/home/nikolaus/Entwicklung/trufont/src/ufolib/Lib/ufoLib/glifLib.py", line 583, in writeGlyphToString
    drawPointsFunc(pen)
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/glyph.py", line 379, in drawPoints
    contour.drawPoints(pointPen)
  File "/home/nikolaus/.local/lib/python3.4/site-packages/defconQt-0.3.0-py3.4.egg/defconQt/objects/defcon.py", line 238, in drawPoints
  File "/home/nikolaus/Entwicklung/trufont/src/ufolib/Lib/ufoLib/glifLib.py", line 1513, in endPath
    raise GlifLibError("open contour has loose offcurve point")
ufoLib.glifLib.GlifLibError: open contour has loose offcurve point
```

**Comment by adrientetar** [comment]
See unified-font-object/ufoLib#12.

**Comment by adrientetar** [comment]
There is now elision of trailing offCurves, the rest is on ufoLib.
