### ISSUE TITLE
Crash when removing overlap is clicked with open contours

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#216]
```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 260, in _buttonAction
    button.clicked()
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/tools/removeOverlapButton.py", line 9, in clicked
    self._glyph.removeOverlap()
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/objects/defcon.py", line 179, in removeOverlap
    bGlyph = BooleanGlyph(self).removeOverlap()
  File "/Users/Pathum/src/github.com/trufont/trufont/src/booleanoperations/Lib/booleanOperations/booleanGlyph.py", line 232, in removeOverlap
    return self._booleanMath("union", None)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/booleanoperations/Lib/booleanOperations/booleanGlyph.py", line 192, in _booleanMath
    func(contours, destination.getPointPen())
  File "/Users/Pathum/src/github.com/trufont/trufont/src/booleanoperations/Lib/booleanOperations/booleanOperationManager.py", line 56, in union
    return self._performOperation("union", contours, [], outPen)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/booleanoperations/Lib/booleanOperations/booleanOperationManager.py", line 20, in _performOperation
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/Users/Pathum/src/github.com/trufont/trufont/src/booleanoperations/Lib/booleanOperations/booleanOperationManager.py", line 20, in <listcomp>
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/Users/Pathum/src/github.com/trufont/trufont/src/booleanoperations/Lib/booleanOperations/flatten.py", line 67, in __init__
    contour.drawPoints(pointPen)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/booleanoperations/Lib/booleanOperations/booleanGlyph.py", line 74, in drawPoints
    pointPen.addPoint(pt=pt, segmentType=segmentType, smooth=smooth, name=name)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/booleanoperations/Lib/booleanOperations/flatten.py", line 341, in addPoint
    assert segmentType != "move"
AssertionError
/Users/Pathum/src/github.com/trufont/trufont.command: line 2: 47923 Abort trap: 6  
```

**Comment by anthrotype** [comment]
this might be related https://github.com/typemytype/booleanOperations/pull/22

**Comment by anthrotype** [comment]
although, admittedly, the [docstring](https://github.com/typemytype/booleanOperations/blob/master/Lib/booleanOperations/booleanOperationManager.py#L10) in `booleanOperationManager.py` says:
```
- Only perform operations on closed contours.
```
so maybe Trufont should not try to send an open contour (starting with a "move" segmentType) to booleanOperations?

**Comment by madig** [comment]
Hm. Idea for the UI: check paths on every point change, gray out "remove overlap" if open contours are found and set its' tooltip to "Open contours found, removing overlaps only works if all contours are closed."

**Comment by adrientetar** [comment]
I don't see why you would want to do this with open contours, but indeed this bug needs fixing. Glyphs deletes open paths when doing remove overlap, robofont closes them before.

**Comment by adrientetar** [comment]
FontLab VI does same as Glyphs.

**Comment by adrientetar** [comment]
5eb9255a72a2049cb758838a710684b0c98e9085
