### ISSUE TITLE
fails to launch on Ubuntu

### ISSUE THREAD

**Issue by n7s** [trufont/trufont#230]
git master fails to launch on Ubuntu 14.04:

Traceback (most recent call last):
  File "/usr/local/bin/trufont", line 9, in <module>
    load_entry_point('defconQt==0.3.0', 'gui_scripts', 'trufont')()
  File "/usr/local/lib/python3.4/dist-packages/defconQt-0.3.0-py3.4.egg/defconQt/__main__.py", line 36, in main
    app.loadGlyphList()
  File "/usr/local/lib/python3.4/dist-packages/defconQt-0.3.0-py3.4.egg/defconQt/fontView.py", line 96, in loadGlyphList
    glyphListPath = settings.value("settings/glyphListPath", type=str)
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10

**Comment by adrientetar** [comment]
Are you using Qt 5.5+?

**Comment by n7s** [comment]
Ubuntu 14.04 (trusty - the current LTS) has pyqt 5.2.1+dfsg-1ubuntu1 
http://packages.ubuntu.com/source/trusty/pyqt5

**Comment by n7s** [comment]
the error is gone on Debian Sid using pyqt5-dev 5.5.1

**Comment by adrientetar** [comment]
It's only an issue on the stock 5.3.0.
