### ISSUE TITLE
[bezierMath] lineDistance raises "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#254]
`bezierMath.lineProjection` returns None if the point cannot be projected on the segment. However `bezierMath.lineDistance` that calls `lineProjection` does not check if the returned value is None, and therefore makes Python crash with `TypeError: 'NoneType' object is not iterable`.

Calling `lineProjection` with  `ditchOutOfSegment=False` prevents it to return None and fixes the issue.
`ditchOutOfSegment` argument is True by default.

**Comment by adrientetar** [comment]
Good point. Locally I removed ditchOutOfSegment and return t as well so caller can do what they want depending on t.

**Comment by pathumego** [comment]
@adrientetar Trufont keeps crashing on the head, gives following. I think it is the same issue. Is it? 
I had to switch to the binary build for now.

```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1030, in mousePressEvent
    self._redirectEvent(event, self._currentTool.mousePressEvent, True)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1002, in _redirectEvent
    callback(event)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/tools/selectionTool.py", line 261, in mousePressEvent
    self._computeLineClick(event.localPos())
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/tools/selectionTool.py", line 100, in _computeLineClick
    prev.x, prev.y, point.x, point.y, pos.x(), pos.y())
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/util/bezierMath.py", line 45, in lineDistance
    projX, projY = lineProjection(x1, y1, x2, y2, x, y)
TypeError: 'NoneType' object is not iterable
/Users/Pathum/src/github.com/trufont/trufont.command: line 2: 65018 Abort trap: 6 
```

**Comment by adrientetar** [comment]
62e678bfdb489e1d567ac813451907256a6c7113 should fixup until the dev branch is merged.
