### ISSUE TITLE
Error on launch on mac 

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#262]
<img width="609" alt="screen shot 2016-04-16 at 10 50 55 am" src="https://cloud.githubusercontent.com/assets/6846609/14580309/806e0032-03c1-11e6-99b1-7223380f1edc.png">

```
Traceback (most recent call last):
  File ":/trufont/objects/application.py", line 41, in event
  File ":/trufont/objects/application.py", line 62, in loadGlyphList
  File "bootstrap.py", line 969, in _find_and_load
  File "bootstrap.py", line 956, in _find_and_load_unlocked
ImportError: No module named 'trufont.util'

```

**Comment by adrientetar** [comment]
d0dec5bfb3acf67dd8b659ddc2d0d63b7f1269b7
