### ISSUE TITLE
Current trufont source won't run

### ISSUE THREAD

**Issue by kelvin13** [trufont/trufont#266]
Right now, following all the instructions in INSTALL.md i get
```

$ python3 -m trufont
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/trufont-0.4.0-py3.4.egg/trufont/__main__.py", line 3, in <module>
    from trufont.objects.application import Application
  File "/usr/local/lib/python3.4/dist-packages/trufont-0.4.0-py3.4.egg/trufont/objects/application.py", line 8, in <module>
    from trufont.windows.fontWindow import FontWindow
  File "/usr/local/lib/python3.4/dist-packages/trufont-0.4.0-py3.4.egg/trufont/windows/fontWindow.py", line 14, in <module>
    from trufont.windows.inspectorWindow import InspectorWindow
  File "/usr/local/lib/python3.4/dist-packages/trufont-0.4.0-py3.4.egg/trufont/windows/inspectorWindow.py", line 2, in <module>
    from defconQt.controls.accordionBox import AccordionBox
  File "/home/kelvin/trufont/src/defconqt/Lib/defconQt/controls/accordionBox.py", line 12, in <module>
    from PyQt5.QtWidgets import (
ImportError: cannot import name 'QProxyStyle'
```

**Comment by adrientetar** [comment]
Currently you need PyQt 5.5+ and so Qt 5.5+ to run the app.

**Comment by kelvin13** [comment]
I have QT 5.6 but I can't get PyQT 5.5+, i read somewhere that you need to be on ubuntu 16.04 to get it

**Comment by adrientetar** [comment]
Not from the builtin packages but you can [install it from source](http://pyqt.sourceforge.net/Docs/PyQt5/installation.html).

**Comment by kelvin13** [comment]
> SIP must be installed before building and using PyQt5

…of course it does.

**Comment by adrientetar** [comment]
#270 updated instructions.
