### ISSUE TITLE
Crash on opening glyph

### ISSUE THREAD

**Issue by kelvin13** [trufont/trufont#267]
I get

```
Traceback (most recent call last):
  File "/home/kelvin/trufont/Lib/trufont/windows/fontWindow.py", line 232, in _glyphActivated
    glyphWindow = GlyphWindow(glyph, self)
  File "/home/kelvin/trufont/Lib/trufont/windows/glyphWindow.py", line 114, in __init__
    self.view.setFocus()
TypeError: setFocus() missing 1 required positional argument: 'value'
```

whenever I try to open a glyph

**Comment by adrientetar** [comment]
https://github.com/trufont/trufont/commit/e8b87078bc69a12a0a964b78599dfd53001feb3a
