### ISSUE TITLE
Crash on Windows when zooming in 

### ISSUE THREAD

**Issue by nclm** [trufont/trufont#292]
I downloaded TruFont 0.4.0, launched it in Windows 10, opened a font, zoomed in the glyphs grid, and:

![](https://cloud.githubusercontent.com/assets/923008/16733019/09ca0d7e-4780-11e6-97f6-8f4b29ee1ca7.PNG)

The traceback reads as:
> Traceback (most recent call last):
  File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\controls\glyphCellView.py", line 274, in paintEvent
  File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\controls\glyphCellView.py", line 87, in _getCurrentRepresentation
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 337, in getRepresentation
  File "C:\Users\Admin\Downloads\trufont\Lib\trufont\representationFactories\glyphCellFactory.py", line 18, in TFGlyphCellFactory
  File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\representationFactories\glyphCellFactory.py", line 96, in getPixmap
  File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\representationFactories\glyphCellFactory.py", line 140, in drawCellHorizontalMetrics
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

The last message is repeated again:
> unsupported operand type(s) for *: 'NoneType' and 'float'

And a last one before crashing:
![](https://cloud.githubusercontent.com/assets/923008/16733109/7dc02858-4780-11e6-98af-5519c7bcf6fb.png)

I doesn’t happen with an empty font, or with a new font with some glyphs just created in TruFont.

**Comment by adrientetar** [comment]
This is trufont/trufont#268. Fixed but needs a new release.

**Comment by adrientetar** [comment]
A workaround is to define all of ascender, descender, xHeight, capHeight.
