### ISSUE TITLE
Shutdown message when trying to open a character of a font

### ISSUE THREAD

**Issue by insanetesterftw** [trufont/trufont#303]
Windows 7 64
Recent TruFont release: 0.4.0

How did I get there:

1) Import font (ttf)
2) Double click character. Message is shown.

> TruFont encountered a problem and must shutdown.
> 
> Traceback (most recent call last):
>   File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\controls\glyphView.py", line 522, in paintEvent
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\windows\glyphWindow.py", line 570, in drawFillAndStroke
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\tools\drawing.py", line 133, in drawGlyphFillAndStroke
>   File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 337, in getRepresentation
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\representationFactories\glyphViewFactory.py", line 90, in FilterSelectionQPainterPathFactory
>   File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 337, in getRepresentation
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\representationFactories\glyphViewFactory.py", line 46, in FilterSelectionFactory
>   File "C:\Python34\lib\site-packages\defcon\objects\contour.py", line 319, in _get_segments
> AssertionError

Clicking OK just shows the same message. Clicking CLOSE closes the program.

**Comment by adrientetar** [comment]
I think this was fixed as well, off the top of my head. Again if you could try to reproduce on master that would be helpful for me to track down. Thanks for the reports!

**Comment by insanetesterftw** [comment]
Is a compiled version available?

**Comment by adrientetar** [comment]
No.

**Comment by adrientetar** [comment]
Running from source can be done easily, given python3:
easy_install pip
pip3 install PyQt5
pip3 install -r requirements.txt
pip3 install -e .
trufont

**Comment by insanetesterftw** [comment]
OK. Sigh!

The correct steps to install all of that (64-bit versions) on Windows 7 64 SP1:

- Install the most recent version of Python3 because PyQt5 will not install otherwise
- Install PyQt5 using command: **pip install PyQt5**
- Install Cython using command: **pip install Cython**. This is important because of booleanOperations
- Issue the command: **pip install -r requirements.txt**

After all this it still fails with the following error message:

>Installing collected packages: fonttools, ufoLib, defcon, defconQt, booleanOperations, extractor, ufo2ft, husl
  Running setup.py develop for fonttools
  Running setup.py develop for ufoLib
  Running setup.py develop for defcon
  Running setup.py develop for defconQt
  Running setup.py develop for booleanOperations
    Complete output from command "c:\program files\python35\python.exe" -c "import setuptools, tokenize;__file__='G:\\Applications\\trufont\\src\\booleanoperations\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    Development mode: Compiling Cython modules from .pyx sources.
    running develop
    running egg_info
    writing dependency_links to Lib\booleanOperations.egg-info\dependency_links.txt
    writing Lib\booleanOperations.egg-info\PKG-INFO
    writing top-level names to Lib\booleanOperations.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Lib\booleanOperations.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Lib\booleanOperations.egg-info\SOURCES.txt'
    running build_ext
    cythoning cppWrapper/pyClipper.pyx to cppWrapper\pyClipper.cpp
    building 'booleanOperations.pyClipper' extension
    error: Unable to find vcvarsall.bat

>    ----------------------------------------
> Command ""c:\program files\python35\python.exe" -c "import setuptools, tokenize;__file__='G:\\Applications\\trufont\\src\\booleanoperations\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in G:\Applications\trufont\src\booleanoperations\

**Comment by adrientetar** [comment]
booleanOperations is a C++ package so you need a compiler, that would be Visual Studio on Windows. But you can install binary package instead:
pip install --find-links https://github.com/typemytype/booleanOperations/releases/latest booleanOperations

**Comment by anthrotype** [comment]
We can add the --find-links trick to the pip requirements.txt itself, if you want.

**Comment by adrientetar** [comment]
sgtm

**Comment by insanetesterftw** [comment]
OK. That worked! It seemed like I would have to install the whole Visual Studio and  wasn't willing to do that!

I also left comments on the @anthrotype commit to the requirements.txt file.

I will now test this new to see if the crashes still happen.

**Comment by adrientetar** [comment]
Closing for lack of activity.
