### ISSUE TITLE
TruFont crashes #2

### ISSUE THREAD

**Issue by insanetesterftw** [trufont/trufont#304]
Windows 7 64
TruFont 0.4.0

Steps:

1) Import font (pfb/pfm)
2) Double click character
3) Create new layer, select tool (pen), click inside window
4) The following message is shown:

> TruFont encountered a problem and must shutdown.
> list index out of range
> 
> Traceback (most recent call last):
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\windows\glyphWindow.py", line 687, in mouseMoveEvent
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\windows\glyphWindow.py", line 745, in _redirectEvent
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\drawingTools\penTool.py", line 128, in mouseMoveEvent
>   File "C:\Python34\lib\site-packages\defcon\objects\contour.py", line 238, in __getitem__
> IndexError: list index out of range

Clicking OK dismisses the warning window.

Then, with the same tool selected (pen), clicking inside the window again provokes nothing, but, clicking inside the very small square over the line (sorry, don't know the correct term) causes new error message:

> TruFont encountered a problem and must shutdown.
> illegal line segment point count: 2
> 
> Traceback (most recent call last):
>   File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\controls\glyphView.py", line 522, in paintEvent
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\windows\glyphWindow.py", line 570, in drawFillAndStroke
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\tools\drawing.py", line 129, in drawGlyphFillAndStroke
>   File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 337, in getRepresentation
>   File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\representationFactories\glyphViewFactory.py", line 27, in NoComponentsQPainterPathFactory
>   File "C:\Python34\lib\site-packages\defcon\objects\glyph.py", line 369, in draw
>   File "C:\Python34\lib\site-packages\defcon\objects\glyph.py", line 379, in drawPoints
>   File "C:\Users\Admin\Downloads\trufont\Lib\trufont\objects\defcon.py", line 392, in drawPoints
>   File "C:\Python34\lib\site-packages\ufoLib\pointPen.py", line 132, in endPath
>   File "C:\Python34\lib\site-packages\ufoLib\pointPen.py", line 178, in _flushContour
> AssertionError: illegal line segment point count: 2

Clicking OK shows the same message again. Clicking CLOSE, closes the program.

PS: By the way, those small symbols over the lines to control them are very difficult to select and control.

**Comment by adrientetar** [comment]
The pen tool works for me on a non-foreground layer. Maybe this is fixed already.

> PS: By the way, those small symbols over the lines to control them are very difficult to select and control.

Yes, that was addressed in f7166a15751f25f76c30e1af4bacfabc69c92e97. You may want to run from the master and see if things are improved.

**Comment by adrientetar** [comment]
Closing for lack of activity.
