### ISSUE TITLE
Crash #4

### ISSUE THREAD

**Issue by insanetesterftw** [trufont/trufont#306]
Windows 7 64
TruFont 0.4.0

Steps:

1) Import font (ttf)
2) Double-click a character
3) Select a tool (ruler)
4) Draw a "triangle" over the character with the ruler tool
5) Double click anywhere over this selection. The "triangle" drawn over the character will immediately disappear.
6) The following message is shown:

>TruFont encountered a problem and must shutdown.

>Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\trufont\Lib\trufont\windows\glyphWindow.py", line 696, in mouseReleaseEvent
  File "C:\Users\Admin\Downloads\trufont\Lib\trufont\windows\glyphWindow.py", line 745, in _redirectEvent
  File "C:\Users\Admin\Downloads\trufont\Lib\trufont\drawingTools\rulerTool.py", line 59, in mouseReleaseEvent
TypeError: 'NoneType' object is not subscriptable

**Comment by adrientetar** [comment]
056b26841d50d2d697ef643abacb3e16d2f48f88
