### ISSUE TITLE
Drawing font guidelines is broken

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#311]
Opening any glyph in [Mada-Medium.ufo](https://github.com/khaledhosny/mada/tree/master/sources/Mada-Medium.ufo) causes the following error followed by a segfault:
```
Traceback (most recent call last):
  File "/defconQt/Lib/defconQt/controls/glyphView.py", line 558, in paintEvent
    self.drawGlyphLayer(painter, glyph, layerName)
  File "/trufont/Lib/trufont/windows/glyphWindow.py", line 580, in drawGlyphLayer
    super().drawGlyphLayer(painter, glyph, layerName)
  File "/defconQt/Lib/defconQt/controls/glyphView.py", line 436, in drawGlyphLayer
    self.drawGuidelines(painter, glyph, layerName)
  File "/trufont/Lib/trufont/windows/glyphWindow.py", line 587, in drawGuidelines
    drawText=drawText)
  File "/trufont/Lib/trufont/tools/drawing.py", line 120, in drawFontGuidelines
    _drawGuidelines(painter, font.guidelines, scale, rect, color=color)
  File "/trufont/Lib/trufont/tools/drawing.py", line 200, in _drawGuidelines
    textX = line.glyph.width + 6 * scale
AttributeError: 'NoneType' object has no attribute 'width'
```
The code is assuming glyph is not None, but this is not the case here.

**Comment by khaledhosny** [comment]
Fixed.
