### ISSUE TITLE
Error opening a Type 1 (PFB)

### ISSUE THREAD

**Issue by insanetesterftw** [trufont/trufont#317]
Windows 7 (64)
Trufont (downloaded from repository in the 27th)

While trying to open a Type 1 (PFB) file the following message show up:

>ExtractorError

>The was an error reading the Type1 file

>Traceback (most recent call last):
  File "g:\applications\trufont\src\extractor\lib\extractor\__init__.py", line 37, in extractUFO
    func(pathOrFile, destination, doGlyphs=doGlyphs, doInfo=doInfo, doKerning=doKerning, customFunctions=customFunctions.get(format, []))
  File "g:\applications\trufont\src\extractor\lib\extractor\formats\type1.py", line 25, in extractFontFromType1
    extractType1Info(source, destination)
  File "g:\applications\trufont\src\extractor\lib\extractor\formats\type1.py", line 38, in extractType1Info
    _extractType1FontInfo(source, info)
  File "g:\applications\trufont\src\extractor\lib\extractor\formats\type1.py", line 47, in _extractType1FontInfo
    sourceInfo = source["FontInfo"]
  File "g:\applications\trufont\src\fonttools\lib\fontTools\t1Lib\__init__.py", line 79, in __getitem__
    self.parse()
  File "g:\applications\trufont\src\fonttools\lib\fontTools\t1Lib\__init__.py", line 89, in parse
    subrs = self.font["Private"]["Subrs"]
KeyError: 'Subrs'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "g:\applications\trufont\lib\trufont\windows\fontWindow.py", line 395, in importFile
    font.extract(path)
  File "g:\applications\trufont\lib\trufont\objects\defcon.py", line 91, in extract
    extractor.extractUFO(path, self, fileFormat)
  File "g:\applications\trufont\src\extractor\lib\extractor\__init__.py", line 42, in extractUFO
    raise ExtractorError("There was an error reading the %s file." % format)
extractor.exceptions.ExtractorError: There was an error reading the Type1 file.

**Comment by insanetesterftw** [comment]
FontForge is able to open the file.

PS: The error window is very small and non-resizable.

**Comment by anthrotype** [comment]
Please open an issue over at github.com/behdad/fonttools, posdibly attaching the font file.
