### ISSUE TITLE
[Glyph window] Carsh

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#324]
When I try use `Go to Glyph` on right click menu on canvas to open a component this happens. 
on Version 0.5.0 ea1e495 mac

```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/objects/application.py", line 57, in _focusWidgetChanged
    self.updateMenuBar()
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/objects/application.py", line 235, in updateMenuBar
    window.setupMenu(menuBar)
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/windows/glyphWindow.py", line 86, in setupMenu
    fileMenu.fetchAction(Entries.File_Save, fontWindow.saveFile)
AttributeError: 'QWidget' object has no attribute 'saveFile'

```

**Comment by adrientetar** [comment]
6335a4f1edbece4ee713fb7221f5a5d53be2e853
