### ISSUE TITLE
Can’t save any font

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#325]
```
Traceback (most recent call last):
  File "/trufont/Lib/trufont/windows/fontWindow.py", line 322, in saveFile
    self._font.save(path, ufoFormatVersion)
  File "/trufont/Lib/trufont/objects/defcon.py", line 104, in save
    path, formatVersion, removeUnreferencedImages, progressBar)
  File "/defcon/Lib/defcon/objects/font.py", line 711, in save
    writer = UFOWriter(path, formatVersion=formatVersion)
  File "/ufoLib/Lib/ufoLib/__init__.py", line 566, in __init__
    metaInfo = self._getPlist(METAINFO_FILENAME)
  File "/ufoLib/Lib/ufoLib/__init__.py", line 101, in _getPlist
    path = os.path.join(self._path, fileName)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'bool'
```

For some reason `saveFile` is getting `False` for `path` instead on `None`.

**Comment by adrientetar** [comment]
6335a4f1edbece4ee713fb7221f5a5d53be2e853
