### ISSUE TITLE
[matrics window] Crash

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#326]
I opened some glyphs in the Matrics Window and double click on a glyph to edit it and this happens. And clicking ignore, close, ok gives the same result; error dialog closes, and the same dialog pops up.

Mac  Version 0.5.0 89b3ad6
```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/objects/application.py", line 57, in _focusWidgetChanged
    self.updateMenuBar()
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/objects/application.py", line 235, in updateMenuBar
    window.setupMenu(menuBar)
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/windows/glyphWindow.py", line 86, in setupMenu
    fileMenu.fetchAction(Entries.File_Save, fontWindow.saveFile)
AttributeError: 'MetricsWindow' object has no attribute 'saveFile'

```

**Comment by adrientetar** [comment]
29f49e33a6122b6cf29af7457488344e0c39859b
