### ISSUE TITLE
[glyph window] Go to glyph behavior

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#327]
When I open a glyph with components and open a component with `Go To Glyph` in right click menu the componant opens in a new glyph window. But when the focus is in the new window, all the menu items are grayed out and non of the shortcuts work except for tools shortcuts.

**Comment by adrientetar** [comment]
Is this fixed now?

**Comment by pathumego** [comment]
Now I get this on `Go to Glyph`

```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/objects/application.py", line 57, in _focusWidgetChanged
    self.updateMenuBar()
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/objects/application.py", line 235, in updateMenuBar
    window.setupMenu(menuBar)
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/windows/glyphWindow.py", line 86, in setupMenu
    fileMenu.fetchAction(Entries.File_Save, fontWindow.saveFile)
AttributeError: 'QWidget' object has no attribute 'saveFile'

```

**Comment by adrientetar** [comment]
Cannot repro OSX 10.11.6

**Comment by pathumego** [comment]
I tired with a fresh clone of the repo and its working. Thanks
