### ISSUE TITLE
[inspector] Glyph renaming crash

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#332]
When I try to rename any glyph this happens.
On 8e99dde 

```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/.venv/lib/python3.5/site-packages/trufont/windows/fontWindow.py", line 224, in _selectionChanged
    self._updateGlyphActions()
  File "/Users/Pathum/src/github.com/trufont/trufont/.venv/lib/python3.5/site-packages/trufont/windows/fontWindow.py", line 499, in _updateGlyphActions
    self._undoAction.disconnect()
TypeError: disconnect() of all signals failed

```

**Comment by adrientetar** [comment]
2894be58ad93c7d6adde419d353e0d81ce51da88
