### ISSUE TITLE
Dragging selection crashes the application

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#345]
```
Traceback (most recent call last):
  File "/defconQt/Lib/defconQt/controls/glyphView.py", line 565, in paintEvent
    self.drawForeground(painter)
  File "/trufont/Lib/trufont/windows/glyphWindow.py", line 642, in drawForeground
    self._currentTool.paint(painter)
  File "/trufont/Lib/trufont/drawingTools/selectionTool.py", line 546, in paint
    painter.fillRect(rect)
TypeError: arguments did not match any overloaded call:
  fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): not enough arguments
  fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRectF'
  fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRectF'
  fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): not enough arguments
  fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRectF'
  fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'QRectF'
  fillRect(self, int, int, int, int, Qt.GlobalColor): argument 1 has unexpected type 'QRectF'
  fillRect(self, QRect, Qt.GlobalColor): argument 1 has unexpected type 'QRectF'
  fillRect(self, QRectF, Qt.GlobalColor): not enough arguments
  fillRect(self, int, int, int, int, Qt.BrushStyle): argument 1 has unexpected type 'QRectF'
  fillRect(self, QRect, Qt.BrushStyle): argument 1 has unexpected type 'QRectF'
  fillRect(self, QRectF, Qt.BrushStyle): not enough arguments
```

**Comment by adrientetar** [comment]
Thanks, 277cf97f512d61ae0bab75d495e2bd2895c72d1f.
