### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#35]
Crash from git master - I was just drawing an "A" in a new file
```
$ python3 -m defconQt
Traceback (most recent call last):
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1534, in mouseMoveEvent
    sel[0]._contour.addPoint((prev.x, prev.y))
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/contour.py", line 594, in addPoint
    self.insertPoint(len(self._points), point)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/contour.py", line 187, in insertPoint
    self.dirty = True
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/base.py", line 319, in _set_dirty
    self.postNotification(self.changeNotificationName)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/base.py", line 212, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "/usr/local/lib/python3.5/site-packages/defcon/tools/notifications.py", line 195, in postNotification
    callback(notificationObj)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/glyph.py", line 1149, in _contourChanged
    self.dirty = True
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/objects/defcon.py", line 57, in _set_dirty
    BaseObject._set_dirty(self, value)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/base.py", line 319, in _set_dirty
    self.postNotification(self.changeNotificationName)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/base.py", line 212, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "/usr/local/lib/python3.5/site-packages/defcon/tools/notifications.py", line 195, in postNotification
    callback(notificationObj)
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1928, in _glyphChanged
    self.activeGlyphChanged()
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1948, in activeGlyphChanged
    self.updateActiveLayerPath()
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 2157, in updateActiveLayerPath
    self._layer, representationKey="defconQt.NoComponentsQPainterPath")
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 2163, in updateLayerPath
    path = glyph.getRepresentation(representationKey)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/base.py", line 244, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/representationFactories/glyphViewFactory.py", line 18, in NoComponentsQPainterPathFactory
    glyph.draw(pen)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/glyph.py", line 361, in draw
    self.drawPoints(pointPen)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/glyph.py", line 371, in drawPoints
    contour.drawPoints(pointPen)
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/objects/defcon.py", line 96, in drawPoints
    pointPen.endPath()
  File "/usr/local/lib/python3.5/site-packages/robofab/pens/pointPen.py", line 97, in endPath
    self._flushContour(segments)
  File "/usr/local/lib/python3.5/site-packages/robofab/pens/adapterPens.py", line 47, in _flushContour
    assert len(points) == 1
AssertionError
Abort trap: 6
```

**Comment by adrientetar** [comment]
Hm yes this assertion breaks when the contour has an invalid numbers of offCurves somewhere. Were you closing the contour when it crashing or just in the middle of drawing it?

**Comment by adrientetar** [comment]
Specially the editor did put an offCurve on a line segment. I'll try to investigate more.

**Comment by davelab6** [comment]
I don't remember exactly, I think I closed the contour and then moved a bcp

**Comment by davelab6** [comment]
@adrientetar can be closed?

**Comment by adrientetar** [comment]
I haven't done anything to fix this, but I've not been able to reproduce it either.

**Comment by adrientetar** [comment]
Should be obsoleted by #150.
