### ISSUE TITLE
Crash on revert.

### ISSUE THREAD

**Issue by madig** [trufont/trufont#369]
1. Make a new font, do something, save.
2. Do some more drawing
3. Revert from the file menu

-> Crash.

Fedora 25 x64, Python 3.5.2, Qt 5.8 installed via pip.

**Comment by adrientetar** [comment]
This seems like #339, I'll take a look.

**Comment by adrientetar** [comment]
I have fixed a few underlying issues locally.

Here's a traceback:

```
Traceback (most recent call last):
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\menu.py", line 85, in <lambda>
    action.triggered.connect(lambda: callback())
  File "c:\users\admin\downloads\trufont\lib\trufont\windows\fontWindow.py", line 554, in reloadFile
    font_ = font.__class__().new()
  File "c:\users\admin\downloads\defcon\lib\defcon\objects\font.py", line 1367, in reloadGlyphs
    self.reloadLayers(layerData)
  File "c:\users\admin\downloads\defcon\lib\defcon\objects\font.py", line 1387, in reloadLayers
    self.layers.reloadLayers(layerData)
  File "c:\users\admin\downloads\defcon\lib\defcon\objects\layerSet.py", line 450, in reloadLayers
    layer.reloadGlyphs(glyphNames)
  File "c:\users\admin\downloads\defcon\lib\defcon\objects\layer.py", line 702, in reloadGlyphs
    self._glyphSet.readGlyph(glyphName=glyphName, glyphObject=glyph, pointPen=pointPen)
  File "C:\Program Files\Python36\lib\site-packages\ufoLib\glifLib.py", line 297, in readGlyph
    text = self.getGLIF(glyphName)
  File "C:\Program Files\Python36\lib\site-packages\ufoLib\glifLib.py", line 244, in getGLIF
    fileName = self.contents[glyphName]
KeyError: 'asciitilde'
```

(it's useful if you can attach it when reporting the issue, btw)

**Comment by adrientetar** [comment]
25ddd7e6a322d21fa5a4e3c58368c8f1e7523afd should fix it
