### ISSUE TITLE
Export error: unknown glyph class

### ISSUE THREAD

**Issue by jeffmcneill** [trufont/trufont#376]
Running TruFont on OSX 10.10. I open Hack-Regular.ufo  (https://github.com/chrissimpkins/Hack/tree/master/source/ufo/vfb2ufo), add try and Export and get this error:

/var/folders/k2/0_gr0xvj6wj1fyyz35n817cc0000gn/t/tmpuav1t8h_:59:9: unknown glyph class @aalt3

Note that aalt3 is viewable in the Group Info as a set of glyphs 0-9. Even after deleting that group, the same error happens. Unable to export.

More error info:

Traceback (most recent call last):
  File ":/trufont/windows/fontWindow.py", line 384, in exportFile
  File ":/trufont/objects/defcon.py", line 126, in export
  File ":/defcon/objects/base.py", line 337, in getRepresentation
  File ":/trufont/representationFactories/openTypeFactory.py", line 5, in TTFontFactory
  File ":/ufo2ft/__init__.py", line 29, in compileOTF
  File ":/ufo2ft/__init__.py", line 18, in _compile
  File ":/ufo2ft/makeotfParts.py", line 40, in compile
  File ":/ufo2ft/makeotfParts.py", line 188, in setupFile_featureTables
  File ":/fontTools/feaLib/builder.py", line 13, in addOpenTypeFeatures
  File ":/fontTools/feaLib/builder.py", line 50, in build
  File ":/fontTools/feaLib/parser.py", line 40, in parse
  File ":/fontTools/feaLib/parser.py", line 820, in parse_feature_block_
  File ":/fontTools/feaLib/parser.py", line 872, in parse_block_
  File ":/fontTools/feaLib/parser.py", line 543, in parse_substitute_
  File ":/fontTools/feaLib/parser.py", line 246, in parse_glyph_pattern_
  File ":/fontTools/feaLib/parser.py", line 181, in parse_glyphclass_
fontTools.feaLib.error.FeatureLibError: /var/folders/k2/0_gr0xvj6wj1fyyz35n817cc0000gn/T/tmpuav1t8h_:59:9: Unknown glyph class @aalt3

**Comment by jeffmcneill** [comment]
If I just take the .otf from the build directory, there is no problem importing, then exporting it. It is only in opening from the source that the error happens.

**Comment by adrientetar** [comment]
This sounds like the issue with old UFOs exported from Fontlab where it defines the groups in groups.plist instead of in the feature file (which is invalid, the feature file should be self-contained – see unified-font-object/ufo-spec#23).  
I think the newest vfb2ufo should export groups properly, let me take a look.

**Comment by adrientetar** [comment]
Actually can you export with the new vfb2ufo and see if that fixes the issue?

**Comment by jeffmcneill** [comment]
Hi, yes it is working for me now, no errors. Thanks.

**Comment by jeffmcneill** [comment]
Sorry, same problem as before.

**Comment by adrientetar** [comment]
Well, it just means the file is invalid. Do you have `@aalt3` defined in the feature file?

**Comment by jeffmcneill** [comment]
I'm using the Hack ufo. I've opened a support issue over there as well: 

https://github.com/chrissimpkins/Hack/issues/244

UFO: 
https://github.com/chrissimpkins/Hack/tree/master/source/ufo/vfb2ufo

**Comment by adrientetar** [comment]
Yea as I said, this file is invalid. You need to take the groups in groups.plist and define them in features.fea, or delete the contents of feature.fea (this will remove the OpenType features but the font will compile properly).

It seems that's a vfb2ufo issue that was never fixed. cc @twardoch
Alternatively you might want to try the UFOCentral script to export from within Fontlab Studio: https://github.com/typesupply/fontlab-scripts/blob/master/UFOCentral.py

**Comment by chrissimpkins** [comment]
@adrientetar How are you testing for valid UFO source? Was this a manual inspection or is there software that we can use to improve our UFO source for future users?

**Comment by adrientetar** [comment]
I just saw Unknown glyph class that tells you groups are not defined in the feature file as they should (fontlab tools export to groups.plist which is incorrect, the bug was reported to them but I think they aren't actively developing the tool these days).

You can test the UFO source by compiling with ufo2ft or the fontmake wrapper and checking that there's no crash and diffing against expected output.

**Comment by chrissimpkins** [comment]
@adrientetar Thank you!
