### ISSUE TITLE
Trying to delete a "qcurve" crashes TruFont

### ISSUE THREAD

**Issue by DeeDeeG** [trufont/trufont#381]
Hi all, I am working on Noto Emoji trying to edit some glyphs, and it crashes every time I try to cut or delete quadratic curves.

The error message is:

> TruFont has encountered a problem and must shutdown.
> unknown segment type: qcurve

Steps to Reproduce:

- get noto emoji:

git clone https://github.com/googlei18n/noto-source/

- open noto emoji in TruFont:

noto-source/src/NotoEmoji/NotoEmoji-Regular.ufo/metainfo.plist

- double-click a glyph and start deleting points on various curves.

Expected: Able to edit these curves

Actual: TruFont gives an error message and crashes.

**Comment by DeeDeeG** [comment]
Here is the traceback:
```
Traceback (most recent call last):
  File "c:\users\joseph\venv\lib\site-packages\trufont\windows\glyphWindow.py", line 706, in keyPressEvent
    self._redirectEvent(event, self._currentTool.keyPressEvent)
  File "c:\users\joseph\venv\lib\site-packages\trufont\windows\glyphWindow.py", line 797, in _redirectEvent
    callback(event)
  File "c:\users\joseph\venv\lib\site-packages\trufont\drawingTools\selectionTool.py", line 381, in keyPressEvent
    removeUIGlyphElements(glyph, preserveShape)
  File "c:\users\joseph\venv\lib\site-packages\trufont\tools\uiMethods.py", line 229, in removeUIGlyphElements
    removeUISelection(contour, preserveShape)
  File "c:\users\joseph\venv\lib\site-packages\trufont\tools\uiMethods.py", line 176, in removeUISelection
    contour.removeSegment(index, preserveShape)
  File "c:\users\joseph\venv\lib\site-packages\defcon\objects\contour.py", line 362, in removeSegment
    raise NotImplementedError("unknown segment type: %s" % segment[-1].segmentType)
NotImplementedError: unknown segment type: qcurve
```

**Comment by adrientetar** [comment]
02ae32dfbdca902edd881adb45cefe0ec06db03f

**Comment by DeeDeeG** [comment]
Hi, I got the error again. (Working on the same font file.) New traceback below:

```
Traceback (most recent call last):
  File "/home/mint/trufont/Lib/trufont/controls/glyphCanvasView.py", line 413, in mouseReleaseEvent
    self._redirectEvent(event, self._currentTool.mouseReleaseEvent, True)
  File "/home/mint/trufont/Lib/trufont/controls/glyphCanvasView.py", line 499, in _redirectEvent
    callback(event)
  File "/home/mint/trufont/Lib/trufont/drawingTools/knifeTool.py", line 119, in mouseReleaseEvent
    contour.splitAndInsertPointAtSegmentAndT(index, t / prev)
  File "/home/mint/VENV/lib/python3.5/site-packages/defcon/objects/contour.py", line 515, in splitAndInsertPointAtSegmentAndT
    self._splitAndInsertAtSegmentAndT(segmentIndex, t, True)
  File "/home/mint/VENV/lib/python3.5/site-packages/defcon/objects/contour.py", line 540, in _splitAndInsertAtSegmentAndT
    raise NotImplementedError("unknown segment type: %s" % segmentType)
NotImplementedError: unknown segment type: qcurve
```
