### ISSUE TITLE
Crash on trying to insert into recent list

### ISSUE THREAD

**Issue by madig** [trufont/trufont#399]
1. Launch `trufont some.ufo` from the command line
2. Get error message with traceback:

```
Traceback (most recent call last):
  File "/home/nikolaus/.local/bin/trufont", line 9, in <module>
    load_entry_point('trufont==0.6.0.dev0', 'gui_scripts', 'trufont')()
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/__main__.py", line 96, in main
    app.openFile(fontPath)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/application.py", line 379, in openFile
    self._openFile(path, importFile=platformSpecific.mergeOpenAndImport())
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/application.py", line 450, in _openFile
    self._loadUFO(path)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/application.py", line 495, in _loadUFO
    self.setCurrentFile(font.path)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/application.py", line 586, in setCurrentFile
    recentFiles.insert(0, path)
AttributeError: 'str' object has no attribute 'insert'
```
The same error pops up when opening the .ufo from the file menu, but the application won't close on crash.

**Comment by adrientetar** [comment]
It seems your recent files setting is corrupt, does it work if you run in scripting window:

```
from trufont.objects import settings
settings.setRecentFiles([])
```

Commenting out the self.setCurrentFile(font.path) should let TruFont start, otherwise you can clear settings manually in $HOME/.config/TruFont

**Comment by madig** [comment]
The script didn't work, but deleting the config did.

**Comment by madig** [comment]
Clearing the recent list through the menu gives me the same error and traceback again.
