### ISSUE TITLE
NameError: name 'drawComponentsFill' is not defined

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#403]
Open a font, Window menu, Metrics, and I see this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/defconQt/controls/glyphLineView.py", line 658, in paintEvent
    self.paintLeftToRight(painter, event.rect())
  File "/usr/local/lib/python3.6/site-packages/defconQt/controls/glyphLineView.py", line 728, in paintLeftToRight
    self.drawGlyph(painter, glyph, rect, selected=selected)
  File "/usr/local/lib/python3.6/site-packages/defconQt/controls/glyphLineView.py", line 524, in drawGlyph
    self.drawFillAndStroke(painter, g, layerName, rect)
  File "/usr/local/lib/python3.6/site-packages/defconQt/controls/glyphLineView.py", line 597, in drawFillAndStroke
    componentFillColor=fillColor)
  File "/usr/local/lib/python3.6/site-packages/defconQt/tools/drawing.py", line 531, in drawGlyphFillAndStroke
    if drawComponentsFill:
NameError: name 'drawComponentsFill' is not defined
````

I click 'ignore' and the Metrics window opens :) 

Then I get a segfault crash, and see in terminal:

```
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QWidget::repaint: Recursive repaint detected
QPainter::end: Painter ended with 3 saved states
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::end: Painter ended with 3 saved states
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::end: Painter ended with 3 saved states
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::end: Painter ended with 3 saved states
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::end: Painter ended with 3 saved states
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
Segmentation fault: 11
$
```

**Comment by adrientetar** [comment]
Update defconQt. I'll make a new tag.

**Comment by adrientetar** [comment]
a8a4c4f17238a7f8476ef714aa12635ef81b34fe

**Comment by davelab6** [comment]
I propose an update to dev-requirements.txt with the github URLs of all the deps, so that one can simply `pip3 install -U -r dev-requirements.txt` to get all the latest packages from their master branch on github
