### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#413]
When I try to set up from source with a fresh clone this happens. I couldn't figure out what is happening here.

```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/ENV_DIR/bin/trufont", line 7, in <module>
    from trufont.__main__ import main
  File "/Users/Pathum/src/github.com/trufont/ENV_DIR/lib/python3.5/site-packages/trufont/__main__.py", line 4, in <module>
    from trufont.objects.application import Application
  File "/Users/Pathum/src/github.com/trufont/ENV_DIR/lib/python3.5/site-packages/trufont/objects/application.py", line 13, in <module>
    from trufont.windows.inspectorWindow import InspectorWindow
  File "/Users/Pathum/src/github.com/trufont/ENV_DIR/lib/python3.5/site-packages/trufont/windows/inspectorWindow.py", line 1, in <module>
    from defconQt.controls.accordionBox import AccordionBox
ImportError: No module named 'defconQt.controls.accordionBox'
```

**Comment by adrientetar** [comment]
Update trufont.

**Comment by jamadagni** [comment]
Hello I've just done a fresh `pip3 install trufont` as per your instructions but still I am getting the above error. Please help.

**Comment by adrientetar** [comment]
You need to git clone https://github.com/trufont/trufont instead of pip which is very old.
