### ISSUE TITLE
Uncaught exception: Sorting by "Glyph set" when included glyph in set is not in font

### ISSUE THREAD

**Issue by madig** [trufont/trufont#417]
Version: master
1. Import e.g. Ubuntu-R.ttf
2. Sort by glyph set "Latin-default"
3. Get uncaught exception. Ignoring it can lead to random crashes.

```
Traceback (most recent call last):
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/menu.py", line 85, in <lambda>
    action.triggered.connect(lambda: callback())
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/windows/fontWindow.py", line 939, in sortGlyphs
    self._font.sortDescriptor = sortDescriptor
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/defcon.py", line 182, in _set_sortDescriptor
    data=dict(oldValue=oldValue, newValue=value))
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/base.py", line 221, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/tools/notifications.py", line 198, in postNotification
    callback(notificationObj)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/windows/fontWindow.py", line 548, in _sortDescriptorChanged
    font.glyphOrder = glyphNames
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/font.py", line 618, in _set_glyphOrder
    self.postNotification("Font.GlyphOrderChanged", data=dict(oldValue=oldValue, newValue=value))
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/base.py", line 221, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/tools/notifications.py", line 198, in postNotification
    callback(notificationObj)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/windows/fontWindow.py", line 508, in _glyphOrderChanged
    glyphs = [font[name] for name in font.glyphOrder]
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/windows/fontWindow.py", line 508, in <listcomp>
    glyphs = [font[name] for name in font.glyphOrder]
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/font.py", line 219, in __getitem__
    return self._glyphSet[name]
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/layer.py", line 261, in __getitem__
    self.loadGlyph(name)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/defcon.py", line 221, in loadGlyph
    glyph = super().loadGlyph(name)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/layer.py", line 178, in loadGlyph
    raise KeyError("%s not in layer" % name)
KeyError: 'gravecomb not in layer'
```

**Comment by adrientetar** [comment]
I got this while looking into your sort issue 944d4bf0ff03d21dd8db05700dfe11586ec1b7db
