### ISSUE TITLE
Adding glyphs or sorting them may result in uncaught exception

### ISSUE THREAD

**Issue by madig** [trufont/trufont#429]
So I can't seem to reproduce this reliably, but here's what I did:

1. Open my UFO: [Regular Base.zip](https://github.com/trufont/trufont/files/970910/Regular.Base.zip)
2. Add glyphs (with an empty last line if it matters):
```
ellipsis
hungarumlautcomb

```
3. Get exception (sometimes?):
```
Traceback (most recent call last):
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/menu.py", line 85, in <lambda>
    action.triggered.connect(lambda: callback())
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/windows/fontWindow.py", line 922, in addGlyphs
    glyph = self._font.get(name, **params)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/defcon.py", line 90, in get
    return self._glyphSet.get(name, **kwargs)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/defcon.py", line 199, in get
    glyph = self.newGlyph(name)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/objects/defcon.py", line 226, in newGlyph
    glyph = super().newGlyph(name)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/layer.py", line 209, in newGlyph
    self.postNotification("Layer.GlyphAdded", data=(dict(name=name)))
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/base.py", line 221, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/tools/notifications.py", line 198, in postNotification
    callback(notificationObj)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/font.py", line 1050, in _glyphAddedNotificationCallback
    self.updateGlyphOrder(addedGlyph=name)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/font.py", line 649, in updateGlyphOrder
    self.glyphOrder = order
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/font.py", line 618, in _set_glyphOrder
    self.postNotification("Font.GlyphOrderChanged", data=dict(oldValue=oldValue, newValue=value))
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/base.py", line 221, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/tools/notifications.py", line 198, in postNotification
    callback(notificationObj)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/windows/fontWindow.py", line 507, in _glyphOrderChanged
    self._updateGlyphsFromGlyphOrder()
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.6.0.dev0-py3.5.egg/trufont/windows/fontWindow.py", line 536, in _updateGlyphsFromGlyphOrder
    self.glyphCellView.setGlyphs(glyphs)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defconQt/controls/glyphCellView.py", line 767, in setGlyphs
    self._glyphCellWidget.setGlyphs(glyphs)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defconQt/controls/glyphCellView.py", line 127, in setGlyphs
    currentSelection = [self._glyphs[index] for index in self._selection]
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defconQt/controls/glyphCellView.py", line 127, in <listcomp>
    currentSelection = [self._glyphs[index] for index in self._selection]
TypeError: list indices must be integers or slices, not NoneType
```

Sometimes, I get the same exception when sorting.

**Comment by madig** [comment]
I think I nailed this one down:

1. Open some font, open some glyph and modify something
2. Go back to the font view
3. Click somewhere on empty space in the view to make sure no glyph is selected
4. Save

This gets me this backtrace:
```
Traceback (most recent call last):
  File "/home/nikolaus/Entwicklung/trufont/Lib/trufont/windows/fontWindow.py", line 485, in _selectionChanged
    glyph = self.glyphCellView.glyphsForIndexes(selection)[0]
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defconQt/controls/glyphCellView.py", line 771, in glyphsForIndexes
    return self._glyphCellWidget.glyphsForIndexes(indexes)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defconQt/controls/glyphCellView.py", line 140, in glyphsForIndexes
    return [self._glyphs[i] for i in indexes]
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defconQt/controls/glyphCellView.py", line 140, in <listcomp>
    return [self._glyphs[i] for i in indexes]
TypeError: list indices must be integers or slices, not NoneType
```
So multiple code paths call `glyphCellView.glyphsForIndexes(selection)` with an empty selection.
