### ISSUE TITLE
Trufont won’t run from OS X command line (QT module missing)

### ISSUE THREAD

**Issue by rdazvd** [trufont/trufont#442]
After setting the virtual environment and running `pip install --upgrade trufont`, trying to run the app from the command line generates the following error:

`~/ENV_DIR/lib/python3.6/site-packages/trufont/windows/inspectorWindow.py", line 1, in <module>
    from defconQt.controls.accordionBox import AccordionBox`
`ModuleNotFoundError: No module named 'defconQt.controls.accordionBox'`

(this is under OS X El Capitan)

**Comment by adrientetar** [comment]
Update trufont.

**Comment by rdazvd** [comment]
Error still shows up. Here’s my entire output:

```
(ENV_DIR) Rafael:~ $ pip install --upgrade trufont
Requirement already up-to-date: trufont in ./ENV_DIR/lib/python3.6/site-packages
Requirement already up-to-date: ufo-extractor>=0.2.0 in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: ufo2ft>=0.3.1 in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: defcon>=0.2.0 in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: fonttools>=3.3.1 in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: husl in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: booleanOperations>=0.6.4 in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: ufoLib>=2.0.0 in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: pyqt5>=5.5.0 in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: defconQt>=0.2.0 in ./ENV_DIR/lib/python3.6/site-packages (from trufont)
Requirement already up-to-date: cu2qu>=1.1.1 in ./ENV_DIR/lib/python3.6/site-packages (from ufo2ft>=0.3.1->trufont)
Requirement already up-to-date: compreffor>=0.4.4 in ./ENV_DIR/lib/python3.6/site-packages (from ufo2ft>=0.3.1->trufont)
Requirement already up-to-date: pyclipper>=1.0.5 in ./ENV_DIR/lib/python3.6/site-packages (from booleanOperations>=0.6.4->trufont)
Requirement already up-to-date: sip<4.20,>=4.19 in ./ENV_DIR/lib/python3.6/site-packages (from pyqt5>=5.5.0->trufont)

(ENV_DIR) Rafael:~ $ trufont
Traceback (most recent call last):
  File "/Users/rafaeldeazevedo/ENV_DIR/bin/trufont", line 7, in <module>
    from trufont.__main__ import main
  File "/Users/rafaeldeazevedo/ENV_DIR/lib/python3.6/site-packages/trufont/__main__.py", line 4, in <module>
    from trufont.objects.application import Application
  File "/Users/rafaeldeazevedo/ENV_DIR/lib/python3.6/site-packages/trufont/objects/application.py", line 13, in <module>
    from trufont.windows.inspectorWindow import InspectorWindow
  File "/Users/rafaeldeazevedo/ENV_DIR/lib/python3.6/site-packages/trufont/windows/inspectorWindow.py", line 1, in <module>
    from defconQt.controls.accordionBox import AccordionBox
ModuleNotFoundError: No module named 'defconQt.controls.accordionBox'
```

**Comment by adrientetar** [comment]
Try to clone the trufont repository rather than pip install it.

**Comment by adrientetar** [comment]
I should put out a new release.

**Comment by pathumego** [comment]
I have the same issue, not been able to run from the latest :(

**Comment by adrientetar** [comment]
Are you unable to git clone https://github.com/trufont/trufont?

**Comment by rdazvd** [comment]
For me, removing the entire directory with `rm -rf` then cloning the repository generates exactly the same output as above.

**Comment by madig** [comment]
> I should put out a new release.

I hope I'm not coming across wrong here, but I'd consider bugs #420, #422, #423, #424, #428, #429, #431 and #437 release blockers 😞

**Comment by tshinnic** [comment]
First I tried plain `pip install --upgrade trufont` and ended up with (trying to remember 0.5.1something).  And got the above error about `accordianBox`.  So then git clone from here and did suggested `pip install --editable .` and `pip install --upgrade -r requirements.txt`.  This says it is 
>  trufont (0.6.0.dev0, c:\toms\study\fonts\tools\trufont\lib)

I finally got program to start using some mashed together experiment
```
import re
import sys
from trufont.__main__ import main
main()
```
from inside trufont\Lib, which clues were from the older/previous trufont.exe in /Scripts/, which had gotten rewritten to a blank trufont.exe sometime.  Joy?  .notdef
Ahh, so is *this* the 'right' way to start from cloned dir?
```
python3 -m trufont \Toms\Study\fonts\fonts\source-sans-pro\Roman\Regular\font.ufo
```

**Comment by anthrotype** [comment]
> I should put out a new release.

@adrientetar yeah, it would be good to have a more recent `trufont` wheel on PyPI, so one can do `pip install trufont` without having to clone first. I can help with that.

**Comment by anthrotype** [comment]
> so is this the 'right' way to start from cloned dir?

@tshinnic If you did `pip install -e .` then you should be able to simply run the `trufont` console script. The editable install will create launchers in the `bin` or `Scripts` folder, but of course you need to ensure those folders are in your environment's `$PATH` variable (or `%PATH%` on windows). 
`python3 -m trufont` also works fine, if you prefer that.
