### ISSUE TITLE
Adding glyphs with "sort font" option results in uncaught exception

### ISSUE THREAD

**Issue by madig** [trufont/trufont#455]
1. Open new font
2. Open "add glyphs" dialog, add some and check the "sort font" option.
3. Uncaught exception.
```
Traceback (most recent call last):
  File "/home/nikolaus/Entwicklung/trufont/Lib/trufont/objects/menu.py", line 85, in <lambda>
    action.triggered.connect(lambda: callback())
  File "/home/nikolaus/Entwicklung/trufont/Lib/trufont/windows/fontWindow.py", line 931, in addGlyphs
    self._font.sortDescriptor = self._font.sortDescriptor
  File "/home/nikolaus/Entwicklung/trufont/Lib/trufont/objects/defcon.py", line 180, in _set_sortDescriptor
    data=dict(oldValue=oldValue, newValue=value))
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/objects/base.py", line 221, in postNotification
    dispatcher.postNotification(notification=notification, observable=self, data=data)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/defcon/tools/notifications.py", line 198, in postNotification
    callback(notificationObj)
  File "/home/nikolaus/Entwicklung/trufont/Lib/trufont/windows/fontWindow.py", line 541, in _sortDescriptorChanged
    if descriptors[0]["type"] == "glyphSet":
TypeError: 'NoneType' object is not subscriptable
```

**Comment by madig** [comment]
Correction: This throws an exception if the user didn't set a sort descriptor first, via the "Sort" dialog.
