### ISSUE TITLE
logging breaks output window

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#518]
This snippet works the first time I run it from the Scripting window:

```python
import logging
logging.basicConfig(level='DEBUG')
logging.info('💩')
```

The second time I click Run it crashes like that:

```
INFO:root:💩

--- Logging error ---
Traceback (most recent call last):
  File "/home/clupo/.pyenv/versions/3.6.3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
  File "/home/clupo/Github/trufont/Lib/trufont/windows/outputWindow.py", line 173, in write
    self.oldStream.write(message)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "/home/clupo/.pyenv/versions/trufont36/bin/trufont", line 11, in <module>
    load_entry_point('trufont', 'gui_scripts', 'trufont')()
  File "/home/clupo/Github/trufont/Lib/trufont/__main__.py", line 106, in main
    sys.exit(app.exec_())
  File "/home/clupo/Github/trufont/Lib/trufont/windows/scriptingWindow.py", line 175, in runScript
    exec(code, global_vars)
  File "<string>", line 3, in <module>
Message: '💩'
Arguments: ()
```

**Comment by anthrotype** [comment]
perhaps you should use a context manager for redirecting standard streams.
there's one in contextlib
https://github.com/python/cpython/blob/3.6/Lib/contextlib.py#L188-L225

**Comment by anthrotype** [comment]
I see.. the problem is, basicConfig is only run once, and by default attaches sys.stderr handler to the root logger; the subsequent times it does nothing. This is by design, because it's meant for quick logging setup, not long running apps.

The first time, the root logger is linked with the current value of sys.stderr; but then you redirect it to a different instance of your OutputStream class every time you runScript, thus the subsequent times it fails to because the old value of sys.stderr (which the root logger is still attached to) is gone...

I'm not sure how we can handle this nicely, maybe the context manager I linked above could work (haven't tried).

For now, I'll just configure logging explicitly at every run (avoiding basicConfig) with something like

```python
import logging
import sys

log = logging.getLogger()
log.setLevel(logging.DEBUG)
handler = logging.StreamHandler(sys.stdout)
log.addHandler(handler)

log.debug('💩')
```
