### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by AndrewChon** [trufont/trufont#520]
I would love to help with it if help would be required. At the beginning I knew none of the shortcut keys and I ended up guessing them :P.

**Comment by pathumego** [comment]
Yes, I suppose v1.0.0 arrive soon and with that we need to get this up.  @adrientetar suggested a while ago that we start with something like [this](http://doc.robofont.com/documentation/workspace/glyph-editor/) 

I started drafting on a google doc [here](https://docs.google.com/spreadsheets/d/1-_vfac84YzPBcFuLQ8SDcwgnu7awm8zKBu-s5fzzzN0/edit#gid=0), but need to be updated with the latest iterations. I've been waiting for v.1.0.0 to arrive. But I suppose there may not be any major changes and we can resume with the doc.

Also a mini video tutorial and a Getting started with Trufont tutorial would be nice.

**Comment by AndrewChon** [comment]
That sounds like a good idea.

**Comment by AndrewChon** [comment]
Is there like a Transform function (like flipping and rotating components) in TruFont?

**Comment by pathumego** [comment]
<img width="250" alt="screen shot 2017-12-11 at 2 18 38 am" src="https://user-images.githubusercontent.com/6846609/33809240-bcde0524-de19-11e7-96c4-b8331c11d507.png">
These work on any selection, path or a contour

**Comment by AndrewChon** [comment]
Thank you.

**Comment by AndrewChon** [comment]
Sorry again. I can't run trufont ;p thru the windows cmd, can you help me out xD

**Comment by adrientetar** [comment]
python -m trufont

**Comment by AndrewChon** [comment]
I know that, but this is the issue:

Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Andrew\ENV_DIR\lib\site-packages\trufont\__main__.py", line 4, in <module>
    from trufont.objects.application import Application
  File "C:\Users\Andrew\ENV_DIR\lib\site-packages\trufont\objects\application.py", line 13, in <module>
    from trufont.windows.inspectorWindow import InspectorWindow
  File "C:\Users\Andrew\ENV_DIR\lib\site-packages\trufont\windows\inspectorWindow.py", line 1, in <module>
    from defconQt.controls.accordionBox import AccordionBox
ModuleNotFoundError: No module named 'defconQt.controls.accordionBox'

**Comment by AndrewChon** [comment]
There seems to be no accordionBox module

**Comment by AndrewChon** [comment]
I will try the 0.6 dev and see if that fixes it.

**Comment by AndrewChon** [comment]
Yep got it!

I will take note of this and add clarifications into a drafted documentary

**Comment by AndrewChon** [comment]
Know I need to know how to make an oncurve point.

**Comment by adrientetar** [comment]
The pen tool is second on the left, double -click a glyph to open it first.

**Comment by AndrewChon** [comment]
ahh okay

**Comment by jansindl3r** [comment]
Hi, has anything changed? I would like to do some work on it, it seems as a meaningful project to me. Though I would need a little guidance, just to see where things are and how they interact. I think the community could build a lot on just a basic example like RoboFont does. I am sure other people would appreciate it as well. 
- how to start building an extension?
- how to compile it and test our contributions

A lot of people in the type community are able to help, we just need to see a little example.
Cheers, Jan

**Comment by madig** [comment]
(TruFont is still alpha quality and currently dormant -- I don't think documentation will help at the moment, sorry!)
