### ISSUE TITLE
Export: FeatureLibError "expected a tag" - can't export

### ISSUE THREAD

**Issue by mray** [trufont/trufont#523]
I exported my Font from the native FontForge format to UFO and opened it in TruFont for export.
Exporting to OTF fails in TruFont, I get this error message:

![image](https://user-images.githubusercontent.com/164785/33882675-27fc1df8-df39-11e7-8793-cd6e75fbe450.png)

```
Traceback (most recent call last):
  File "/home/adrien/trufont/Lib/trufont/windows/fontWindow.py", line 384, in exportFile
  File "/home/adrien/trufont/Lib/trufont/objects/defcon.py", line 122, in export
  File "/home/adrien/trufont/src/defcon/Lib/defcon/objects/base.py", line 337, in getRepresentation
  File "/home/adrien/trufont/Lib/trufont/representationFactories/openTypeFactory.py", line 5, in TTFontFactory
  File "/home/adrien/trufont/src/ufo2ft/Lib/ufo2ft/__init__.py", line 19, in compileOTF
  File "/home/adrien/trufont/src/ufo2ft/Lib/ufo2ft/makeotfParts.py", line 40, in compile
  File "/home/adrien/trufont/src/ufo2ft/Lib/ufo2ft/makeotfParts.py", line 185, in setupFile_featureTables
  File "/home/adrien/trufont/src/fonttools/Lib/fontTools/feaLib/builder.py", line 25, in addOpenTypeFeaturesFromString
  File "/home/adrien/trufont/src/fonttools/Lib/fontTools/feaLib/builder.py", line 16, in addOpenTypeFeatures
  File "/home/adrien/trufont/src/fonttools/Lib/fontTools/feaLib/builder.py", line 76, in build
  File "/home/adrien/trufont/src/fonttools/Lib/fontTools/feaLib/parser.py", line 45, in parse
  File "/home/adrien/trufont/src/fonttools/Lib/fontTools/feaLib/parser.py", line 1009, in parse_feature_block_
  File "/home/adrien/trufont/src/fonttools/Lib/fontTools/feaLib/parser.py", line 1175, in expect_tag_
fontTools.feaLib.error.FeatureLibError: /home/mray/Projects/Puk/git-TEMPLATE2/sources/2-build/Puk-Regular.ufo/features.fea:18:14: Expected a tag
```

**Comment by adrientetar** [comment]
The feature file is invalid: "18:14: Expected a tag"

**Comment by adrientetar** [comment]
Seems you're using an old version I would recommend installing from git master.

**Comment by mray** [comment]
Oh right – a newer version is available, but the [homepage](https://trufont.github.io/) still links to 0.4.0 btw!

Unfortunately 0.5.0 complains about missing dependencies and refuses to start on Ubuntu 17.10
`./TruFont: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`

**Comment by mray** [comment]
After seperately [downloading the required package](https://packages.ubuntu.com/xenial/amd64/libpng12-0/download) TruFont 0.5.0 starts on Ubuntu 17.10.

Upon exporting I get another error now:

![image](https://user-images.githubusercontent.com/164785/33884830-8b8f3bc2-df41-11e7-9ef6-c5eead649346.png)


```
Traceback (most recent call last):
  File ":/trufont/windows/fontWindow.py", line 321, in exportFile
  File ":/trufont/objects/defcon.py", line 133, in export
  File ":/defcon/objects/base.py", line 338, in getRepresentation
  File ":/trufont/representationFactories/openTypeFactory.py", line 6, in TTFontFactory
  File ":/ufo2ft/__init__.py", line 24, in compileOTF
  File ":/ufo2ft/outlineOTF.py", line 98, in compile
  File ":/ufo2ft/outlineOTF.py", line 774, in setupOtherTables
  File ":/ufo2ft/outlineOTF.py", line 821, in setupTable_CFF
  File ":/ufo2ft/fontInfoData.py", line 186, in normalizeStringForPostscript
NameError: name 'tobytes' is not defined
```

**Comment by adrientetar** [comment]
This is how to install: https://gist.github.com/adrientetar/b5163cee9f484a94ca089d7a6e397837
