### ISSUE TITLE
Support getting/setting CurrentGlyph().contour[0].clockWise

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#57]
When I run

```py
glyph = CurrentGlyph()
contour = glyph[0] # get the first contour    
print(contour.clockWise) # get the contour direction
```

I get

```py
Traceback (most recent call last):
  File "/Users/dcrossland/src2/github.com/trufont/trufont/Lib/defconQt/scriptingWindow.py", line 41, in runScript
    exec(code, global_vars)
  File "<string>", line 20, in <module>
AttributeError: 'TContour' object has no attribute 'clockWise'
```

I propose this should get `True` or `False` as it would in RoboFab.

Similarly I propose to be able to set the value too, eg

```py
glyph = CurrentGlyph()
contour = glyph[0] # get the first contour    
print(contour.clockWise) # get the contour direction
contour.clockWise = not contour.clockWise # reverse the contour direction
print(contour.clockWise) # get the contour direction
```

and I propose the RoboFab convenience function to reverse contour direction:

```py
contour.reverseContour()
```

**Comment by adrientetar** [comment]
clockWise does not exist, as the traceback puts out.

**Comment by davelab6** [comment]
Right; should it exist? It exists in http://www.robodocs.info/roboFabDocs/source/objects/RContour.html

**Comment by adrientetar** [comment]
It's clockwise, not clockWise.
