### ISSUE TITLE
Deployment issues on the wx branch

### ISSUE THREAD

**Issue by justvanrossum** [trufont/trufont#587]
I'm using Python 3.6.5 from python.org, on macOS 10.10.5

After cloning the repo, checking out the wx branch, creating a fresh venv, I ran 
`pip install -r requirements.txt`

But that fails with the following error:
```
Could not find a version that satisfies the requirement tfont==0.1.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for tfont==0.1.0 (from -r requirements.txt (line 1))
```
Installing tfont from the repo works, but doesn't install ufoLib2. Installing ufoLib2 manually works.

Installing uharfbuzz=0.2.0 (as per requirements.txt) results in a non-working uharfbuzz. Upgrading to 0.2.1 works.

requirements.txt seems to specify a really old fonttools. I went for the latest release (3.30.0).

I also got the latest skia-pathops (skia-pathops-0.2.0.post2).

By now I think I have everything needed from requirements.txt.

Running `pip install -e .` results in the following error:
```
Obtaining file:///Users/just/code/git/trufont
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833) -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833) -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833) -- Some packages may not be found!
    No local packages or working download links found for setuptools_scm
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/just/code/git/trufont/setup.py", line 40, in <module>
        "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
      File "/Users/just/code/git/trufont/tfvenv/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/Users/just/code/git/trufont/tfvenv/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/just/code/git/trufont/tfvenv/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/just/code/git/trufont/tfvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/just/code/git/trufont/tfvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/Users/just/code/git/trufont/tfvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/Users/just/code/git/trufont/tfvenv/lib/python3.6/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/just/code/git/trufont/tfvenv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/just/code/git/trufont/
```

At which point I am stuck.

**Comment by StefanPeev** [comment]
I've the same problem on Windows 8.1 platform.

**Comment by justvanrossum** [comment]
@davelab6, who do you think can help sort this out?

**Comment by anthrotype** [comment]
Hey Just, if you installed python3.6 from Python.org you need to run the "Install Certificate.command" shell script in the /Applications/Python 3.6 folder, otherwise python can't establish secure ssl connections

**Comment by anthrotype** [comment]
and yeah, the requirements.txt seems outdated, and there are some dependencies that are not available from PyPI (such as [tfont](https://github.com/trufont/tfont)).
At the moment i'm busy with other stuff, but I hope to be able to get back to this soon.

**Comment by justvanrossum** [comment]
Thanks, that was it!
