### ISSUE TITLE
[wx branch] error upon save

### ISSUE THREAD

**Issue by justvanrossum** [trufont/trufont#591]
```
Traceback (most recent call last):
  File "/Users/just/code/git/trufont/src/trufont/windows/fontWindow.py", line 586, in OnSave
    self.save()
  File "/Users/just/code/git/trufont/src/trufont/windows/fontWindow.py", line 252, in save
    TFontConverter().save(self._font, path)
  File "/Users/just/code/git/tfont/src/tfont/converters/tfontConverter.py", line 142, in save
    with open(path, 'w') as file:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
The save seems to be succesful, though (as in: a non-empty .tfont file appears).

**Comment by adrientetar** [comment]
802b1c391c0d36cb18d7c8b16fed4d1f61f3fb9a
