### ISSUE TITLE
ImportError: cannot import name 'writePlistAtomically'

### ISSUE THREAD

**Issue by Grief** [trufont/trufont#594]
```
Traceback (most recent call last):
  File "/home/grief/.local/bin//trufont", line 11, in <module>
    load_entry_point('trufont', 'gui_scripts', 'trufont')()
  File "/home/grief/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/grief/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/home/grief/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/grief/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/grief/github/trufont/Lib/trufont/__main__.py", line 4, in <module>
    from trufont.objects.application import Application
  File "/home/grief/github/trufont/Lib/trufont/objects/application.py", line 13, in <module>
    from trufont.windows.extensionBuilderWindow import ExtensionBuilderWindow
  File "/home/grief/github/trufont/Lib/trufont/windows/extensionBuilderWindow.py", line 8, in <module>
    from trufont.objects.extension import TExtension
  File "/home/grief/github/trufont/Lib/trufont/objects/extension.py", line 4, in <module>
    from ufoLib import _getPlist, UFOLibError, writePlistAtomically
ImportError: cannot import name 'writePlistAtomically'
```

**Comment by anthrotype** [comment]
that function has been removed in ufoLib 3.0.
Please downgrade ufoLib for now, `pip install ufoLib==2.3.2`

**Comment by anthrotype** [comment]
i was never intended to be public anyway, so trufont should not have used it in the first place.

**Comment by madig** [comment]
Fixed it in master by using the `dump` function instead.
