### ISSUE TITLE
WX: Opening Ubuntu-B fails

### ISSUE THREAD

**Issue by madig** [trufont/trufont#598]
Ubuntu-Bold ([test.zip](https://github.com/trufont/trufont/files/2489176/test.zip)), turned into a .tfont with the following code:
```Python
import tfont.converters
tf = tfont.converters.UFOConverter().open("Ubuntu-B.ufo")
tfont.converters.TFontConverter(indent=2).save(tf, "/tmp/test.tfont")
```
On opening the file in Trufont-wx, I get repeated exceptions:
```
Traceback (most recent call last):
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/controls/glyphCellView.py", line 329, in OnPaint
    drawing.drawGlyphFigure(ctx, glyph, cellWidth, cellHeight, color)
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/util/drawing.py", line 160, in drawGlyphFigure
    ctx.FillPath(layer.closedComponentsGraphicsPath, wx.WINDING_RULE)
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/objects/layer.py", line 160, in closedComponentsGraphicsPath
    return self.closedComponentsGraphicsPathFactory()
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/objects/factories.py", line 47, in layerClosedComponentsGraphicsPathFactory
    graphicsPath.AddPath(component.closedGraphicsPath)
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/objects/component.py", line 68, in closedGraphicsPath
    return self.closedGraphicsPathFactory()
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/objects/factories.py", line 11, in componentClosedGraphicsPathFactory
    graphicsPath.AddPath(component.layer.closedGraphicsPath)
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/objects/layer.py", line 167, in closedGraphicsPath
    self.closedGraphicsPathFactory()
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/objects/factories.py", line 55, in layerClosedGraphicsPathFactory
    graphicsPath.AddPath(path.graphicsPath)
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/objects/path.py", line 61, in graphicsPath
    graphicsPath = self._graphicsPath = self.graphicsPathFactory()
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/objects/factories.py", line 92, in pathGraphicsPathFactory
    assert not stack
AssertionError
```
![bildschirmfoto vom 2018-10-17 21-44-53](https://user-images.githubusercontent.com/380829/47115251-e6bd0300-d255-11e8-9e7c-408f5987fa93.png)

**Comment by madig** [comment]
Oh, I think I know what's happening. The foreground layer is all quadratic, so `if point.type == "curve":` never triggers.

**Comment by madig** [comment]
![bildschirmfoto vom 2018-10-17 22-58-16](https://user-images.githubusercontent.com/380829/47118735-31dc1380-d260-11e8-9de6-693e569a8a7e.png)

Art.

**Comment by madig** [comment]
Almost: `(cx2 + cx1) / 2, (cy2 + cy1) / 2`
![bildschirmfoto vom 2018-10-17 23-10-17](https://user-images.githubusercontent.com/380829/47119190-db6fd480-d261-11e8-9741-d44172f2ec57.png)
