### ISSUE TITLE
WX: Opening Ubuntu-B glyphs fails with FeatureLibError

### ISSUE THREAD

**Issue by madig** [trufont/trufont#600]
Ubuntu-Bold ([test.zip](https://github.com/trufont/trufont/files/2489176/test.zip)), turned into a .tfont with the following code:
```Python
import tfont.converters
tf = tfont.converters.UFOConverter().open("Ubuntu-B.ufo")
tfont.converters.TFontConverter(indent=2).save(tf, "/tmp/test.tfont")
```
Opening a glyph results in this Traceback and a mangled UI:
```
Traceback (most recent call last):
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/windows/fontWindow.py", line 505, in OnGlyphActivated
    canvas = self._newTab(glyph)
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/windows/fontWindow.py", line 227, in _newTab
    canvas = GlyphCanvasView(tab, self._font)
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/controls/glyphCanvasView.py", line 34, in __init__
    super().__init__(parent, font)
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/controls/glyphContextView.py", line 51, in __init__
    self._layoutManager = LayoutManager(self)
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/objects/layoutManager.py", line 11, in __init__
    self.updateFeatures()
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/objects/layoutManager.py", line 146, in updateFeatures
    fontFeatures = canvas._font.layoutEngine.features
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/objects/font.py", line 100, in layoutEngine
    layoutEngine = self._layoutEngine = self.layoutEngineFactory()
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/objects/factories.py", line 39, in fontLayoutEngineFactory
    addOpenTypeFeaturesFromString(otf, features)
  File "/home/nikolaus/.virtualenvs/trufont/lib64/python3.7/site-packages/fontTools/feaLib/builder.py", line 31, in addOpenTypeFeaturesFromString
    addOpenTypeFeatures(font, featurefile, tables=tables)
  File "/home/nikolaus/.virtualenvs/trufont/lib64/python3.7/site-packages/fontTools/feaLib/builder.py", line 22, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "/home/nikolaus/.virtualenvs/trufont/lib64/python3.7/site-packages/fontTools/feaLib/builder.py", line 108, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "/home/nikolaus/.virtualenvs/trufont/lib64/python3.7/site-packages/fontTools/feaLib/parser.py", line 89, in parse
    self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: <features>:1:1: Expected feature, languagesystem, lookup, markClass, table, or glyph class definition, got SYMBOL "{"
```

**Comment by madig** [comment]
Oh boy. The code in https://github.com/trufont/trufont/blob/wx/src/trufont/objects/factories.py#L26 `str()`s the `FeatureHeader` class which simply strs it's `__repr__`.

**Comment by madig** [comment]
UFOConverter called `ufo.features` instead of `ufo.features.text`.
