### ISSUE TITLE
Crash due to unsupported operand type(s) for /: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by joshuakraemer** [trufont/trufont#707]
I have generated an UFO font containing box drawing characters using Adobe's box drawing script (http://adobe-type-tools.github.io/box-drawing/) with default settings. The resulting font is attached ([boxes.tar.gz](https://github.com/trufont/trufont/files/4411032/boxes.tar.gz)).

If I try to open this font with TruFont, it crashes with the following message:
```
Traceback (most recent call last):
  File "/home/adrien/trufont/src/defconqt/Lib/defconQt/controls/glyphCellView.py", line 274, in paintEvent
  File "/home/adrien/trufont/src/defconqt/Lib/defconQt/controls/glyphCellView.py", line 87, in _getCurrentRepresentation
  File "/home/adrien/trufont/src/defcon/Lib/defcon/objects/base.py", line 337, in getRepresentation
  File "/home/adrien/trufont/Lib/trufont/representationFactories/glyphCellFactory.py", line 17, in TFGlyphCellFactory
  File "/home/adrien/trufont/Lib/trufont/representationFactories/glyphCellFactory.py", line 28, in __init__
  File "/home/adrien/trufont/src/defconqt/Lib/defconQt/representationFactories/glyphCellFactory.py", line 75, in __init__
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

**Comment by madig** [comment]
Try defining all but the last fontinfo values in http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#generic-dimension-information.

**Comment by joshuakraemer** [comment]
Thanks, this works as a workaround.

**Comment by madig** [comment]
TruFont probably needs to set this on load if it's not defined or work without.
