### ISSUE TITLE
Crash on opening glyph - 'set' object is not subscriptable

### ISSUE THREAD

**Issue by nbromberg** [trufont/trufont#714]
Using the latest version of Trufont, with PyQt5 5.13.0 on mac OS 10.12.6.
Running Trufont from terminal, importing any font file, and then double-clicking on a glyph throws up a dialog box with this error:
`Traceback (most recent call last):
  File "/Users/*****/Library/Python/3.7/lib/python/site-packages/trufont/windows/fontWindow.py", line 355, in openGlyphTab
    self.tabWidget.addTab(_textForGlyphs([glyph]))
  File "/Users/*****/Library/Python/3.7/lib/python/site-packages/trufont/windows/fontWindow.py", line 65, in _textForGlyphs
    if glyph.unicode and chr(glyph.unicode) != glyph.name:
  File "/Users/*****/Library/Python/3.7/lib/python/site-packages/defcon/objects/glyph.py", line 231, in _get_unicode
    return self._unicodes[0]
TypeError: 'set' object is not subscriptable`

**Comment by madig** [comment]
Confirmed. Probably some change in the `ufo-extractor` dependency.
